export const APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND";
export const APPLICATION_STATUS_NOT_UPDATED = "APPLICATION_STATUS_NOT_UPDATED";
export const ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
export const SUPPORTING_USER_NOT_FOUND = "SUPPORTING_USER_NOT_FOUND";
