import {
  APPLICATION_EXCEPTION,
  APPLICATION_EXCEPTION_FULL_SCHEMA,
  HEADER_LARGE,
  HEADER_MEDIUM,
  HEADER_SMALL,
  CURRENCY,
  UPLOADER_FORMAT_AND_SIZE,
} from "@/types/formio/custom-components";

export const FORMIO_CUSTOM_COMPONENTS = {
  title: "SIMS",
  components: {
    HEADER_LARGE,
    HEADER_MEDIUM,
    HEADER_SMALL,
    APPLICATION_EXCEPTION,
    APPLICATION_EXCEPTION_FULL_SCHEMA,
    CURRENCY,
    UPLOADER_FORMAT_AND_SIZE,
  },
};
