export const APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND";
export const INVALID_APPLICATION_EDIT_STATUS =
  "INVALID_APPLICATION_EDIT_STATUS";
export const APPLICATION_STATUS_NOT_UPDATED = "APPLICATION_STATUS_NOT_UPDATED";
export const INVALID_OPERATION_IN_THE_CURRENT_STATUS =
  "INVALID_OPERATION_IN_THE_CURRENT_STATUS";
export const APPLICATION_MSFAA_ALREADY_ASSOCIATED =
  "APPLICATION_MSFAA_ALREADY_ASSOCIATED";
export const SUPPORTING_USER_NOT_FOUND = "SUPPORTING_USER_NOT_FOUND";
export const SUPPORTING_USER_FULL_NAME_NOT_RESOLVED =
  "SUPPORTING_USER_FULL_NAME_NOT_RESOLVED";
export const ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
export const ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE";
export const ASSESSMENT_ALREADY_ASSOCIATED_TO_WORKFLOW =
  "ASSESSMENT_ALREADY_ASSOCIATED_TO_WORKFLOW";
export const ASSESSMENT_ALREADY_ASSOCIATED_WITH_DIFFERENT_WORKFLOW =
  "ASSESSMENT_ALREADY_ASSOCIATED_WITH_DIFFERENT_WORKFLOW";
export const DISBURSEMENT_SCHEDULES_ALREADY_CREATED =
  "DISBURSEMENT_SCHEDULES_ALREADY_CREATED";
export const GC_NOTIFY_PERMANENT_FAILURE_ERROR =
  "GC_NOTIFY_PERMANENT_FAILURE_ERROR";
export const APPLICATION_INVALID_DATA_TO_CREATE_MSFAA_ERROR =
  "APPLICATION_INVALID_DATA_TO_CREATE_MSFAA_ERROR";
export const INVALID_TUITION_REMITTANCE_AMOUNT =
  "INVALID_TUITION_REMITTANCE_AMOUNT";
export const ENROLMENT_NOT_FOUND = "ENROLMENT_NOT_FOUND";
export const ENROLMENT_ALREADY_COMPLETED = "ENROLMENT_ALREADY_COMPLETED";
export const ENROLMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "ENROLMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE";
export const ENROLMENT_CONFIRMATION_DATE_NOT_WITHIN_APPROVAL_PERIOD =
  "ENROLMENT_CONFIRMATION_DATE_NOT_WITHIN_APPROVAL_PERIOD";
export const FIRST_COE_NOT_COMPLETE = "FIRST_COE_NOT_COMPLETE";
export const UNEXPECTED_ERROR_DOWNLOADING_FILE =
  "UNEXPECTED_ERROR_DOWNLOADING_FILE";
export const ECE_DISBURSEMENT_DATA_NOT_VALID =
  "ECE_DISBURSEMENT_DATA_NOT_VALID";
export const FILE_PARSING_ERROR = "FILE_PARSING_ERROR";
export const INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "INVALID_OPERATION_IN_THE_CURRENT_STATE";
export const RESTRICTION_NOT_ACTIVE = "RESTRICTION_NOT_ACTIVE";
export const RESTRICTION_NOT_PROVINCIAL = "RESTRICTION_NOT_PROVINCIAL";

/**
 * Used to cancel a database transaction started using the method as below.
 * @example
 * await myDataSource.transaction(async (transactionalEntityManager) => {
 *   // execute queries using transactionalEntityManager
 * })
 * @see https://typeorm.io/#/transactions
 */
export const DATABASE_TRANSACTION_CANCELLATION =
  "DATABASE_TRANSACTION_CANCELLATION";

/**
 * Disbursement was found, but an attempt to update the record schedule was not successful.
 */
export const DISBURSEMENT_SCHEDULE_NOT_UPDATED =
  "DISBURSEMENT_SCHEDULE_NOT_UPDATED";
/**
 * Disbursement schedule not found.
 */
export const DISBURSEMENT_SCHEDULE_NOT_FOUND =
  "DISBURSEMENT_SCHEDULE_NOT_FOUND";
/**
 * Disbursement schedule is not in the correct state to be updated, which
 * indicates that any of the conditions to perform the update are not met.
 */
export const DISBURSEMENT_SCHEDULE_INVALID_STATE_TO_BE_UPDATED =
  "DISBURSEMENT_SCHEDULE_INVALID_STATE_TO_BE_UPDATED";

/**
 * Unable to save file.
 */
export const FILE_SAVE_ERROR = "FILE_SAVE_ERROR";
/**
 * File hash duplication error.
 * For some scenarios the same file should not be saved more than once for the same student,
 * for instance, T4A files.
 */
export const FILE_HASH_DUPLICATION_ERROR = "FILE_HASH_DUPLICATION_ERROR";
