export const APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND";
export const APPLICATION_STATUS_NOT_UPDATED = "APPLICATION_STATUS_NOT_UPDATED";
export const INVALID_OPERATION_IN_THE_CURRENT_STATUS =
  "INVALID_OPERATION_IN_THE_CURRENT_STATUS";
export const APPLICATION_MSFAA_ALREADY_ASSOCIATED =
  "APPLICATION_MSFAA_ALREADY_ASSOCIATED";
export const SUPPORTING_USER_NOT_FOUND = "SUPPORTING_USER_NOT_FOUND";
export const ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
export const ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE";
export const ASSESSMENT_ALREADY_ASSOCIATED_TO_WORKFLOW =
  "ASSESSMENT_ALREADY_ASSOCIATED_TO_WORKFLOW";
export const DISBURSEMENT_SCHEDULES_ALREADY_CREATED =
  "DISBURSEMENT_SCHEDULES_ALREADY_CREATED";
