export enum Workers {
  AssociateWorkflowInstance = "associate-workflow-instance",
  VerifyApplicationExceptions = "verify-application-exceptions",
  ProgramInfoRequest = "program-info-request",
  CreateIncomeRequest = "create-income-request",
  CheckIncomeRequest = "check-income-request",
  UpdateApplicationStatus = "update-application-status",
  ApplicationChangeRequestApproval = "application-change-request-approval",
  LoadAssessmentConsolidatedData = "load-assessment-consolidated-data",
  UpdateNOAStatus = "update-noa-status",
  SaveAssessmentData = "save-assessment-data",
  SaveDisbursementSchedules = "save-disbursement-schedules",
  AssociateMSFAA = "associate-msfaa",
  CreateSupportingUsers = "create-supporting-users",
  LoadSupportingUserData = "load-supporting-user-data",
  WorkflowWrapUp = "workflow-wrap-up",
  VerifyAssessmentCalculationOrder = "verify-assessment-calculation-order",
}
