export enum AppRoutes {
  StudentRoot = "/student",
  InstitutionRoot = "/institution",
  StudentDashboard = "student-dashboard",
  InstitutionDashboard = "institution-dashboard",
  InstitutionProfile = "institution-profile",
  InstitutionProfileEdit = "institution-profile/edit",
  Login = "login",
  ForbiddenUser = "/forbidden-user",
  LoginWithBusinessBCeID = "login/business-bceid",
  InstitutionManageLocations = "manage-locations",
  AddInstitutionLocation = "add-institution-location",
  EditInstitutionLocation = "edit-institution-location",
  LocationPrograms = "location-programs/location/:locationId",
  LocationProgramsView = "location-programs/location/:locationId/program-view/:programId",
  LocationProgramsCreate = "location-programs/location/:locationId/program-create",
  LocationProgramsEdit = "location-programs/location/:locationId/program-edit/:programId",
  LocationApplications = "location-applications",
  LocationUsers = "location-users",
  ManageInstitutionDesignation = "manage-desgination",
  InstitutionManageUsers = "manage-users",
  DisabledUser = "login/disabled-user",
}
