export enum AppRoutes {
  StudentRoot = "/student",
  InstitutionRoot = "/institution",
  StudentDashboard = "student-dashboard",
  InstitutionDashboard = "institution-dashboard",
  InstitutionProfile = "institution-profile",
  InstitutionProfileEdit = "institution-profile/edit",
  Login = "login",
  ForbiddenUser = "/forbidden-user",
  LoginWithBusinessBCeID = "login/business-bceid",
  InstitutionManageLocations = "manage-locations",
  AddInstitutionLocation = "add-institution-location",
  EditInstitutionLocation = "edit-institution-location",
  LocationPrograms = "location-programs",
  LocationProgramsCreate = "location-programs/:locationId/create",
  LocationOfferings = "location-offerings",
  LocationProgramsOfferingsCreate = "location-offerings/location/:locationId/education-program/:programId/create",
  LocationApplications = "location-applications",
  LocationUsers = "location-users",
  ManageInstitutionDesignation = "manage-desgination",
  InstitutionManageUsers = "manage-users",
  DisabledUser = "login/disabled-user",
}
