require("../../../env_setup_apps");
import { Module } from "@nestjs/common";
import { QueueModule, QueueService } from "@sims/services/queue";
import {
  StartApplicationAssessmentProcessor,
  CancelApplicationAssessmentProcessor,
  ProcessNotificationScheduler,
  IER12IntegrationScheduler,
  CRAResponseIntegrationScheduler,
  CRAProcessIntegrationScheduler,
  SINValidationProcessIntegrationScheduler,
  SINValidationRequestIntegrationScheduler,
  FullTimeMSFAAProcessIntegrationScheduler,
  PartTimeMSFAAProcessIntegrationScheduler,
  PartTimeECertProcessIntegrationScheduler,
  FullTimeECertProcessIntegrationScheduler,
  FullTimeECertFeedbackIntegrationScheduler,
  PartTimeECertFeedbackIntegrationScheduler,
  FullTimeDisbursementReceiptsFileIntegrationScheduler,
  FINProcessProvincialDailyDisbursementsIntegrationScheduler,
  FederalRestrictionsIntegrationScheduler,
  FullTimeMSFAAProcessResponseIntegrationScheduler,
  PartTimeMSFAAProcessResponseIntegrationScheduler,
  SFASIntegrationScheduler,
  ATBCResponseIntegrationScheduler,
} from "./processors";
import {
  DisbursementSchedulerService,
  SequenceControlService,
  WorkflowClientService,
  ZeebeModule,
} from "@sims/services";
import { DatabaseModule } from "@sims/sims-db";
import {
  IER12IntegrationModule,
  IER12IntegrationService,
} from "@sims/integrations/institution-integration/ier12-integration";
import { NotificationsModule } from "@sims/services/notifications";
import {
  SystemUserModule,
  SystemUsersService,
} from "@sims/services/system-users";
import {
  IntegrationDisbursementReceiptService,
  DisbursementScheduleErrorsService,
  IntegrationDisbursementSchedulerService,
  FederalRestrictionService,
  MSFAANumberService,
  ReportService,
  IntegrationRestrictionService,
  SshService,
  StudentAssessmentService as StudentsAssessmentService,
  IntegrationStudentRestrictionService,
} from "@sims/integrations/services";
import {
  DisbursementReceiptIntegrationService,
  DisbursementReceiptProcessingService,
  DisbursementReceiptRequestService,
  ECertFileHandler,
  ECertFullTimeFileFooter,
  ECertFullTimeFileHeader,
  ECertFullTimeIntegrationService,
  ECertPartTimeFileFooter,
  ECertPartTimeFileHeader,
  ECertPartTimeIntegrationService,
  FedRestrictionIntegrationService,
  FedRestrictionProcessingService,
  MSFAAIntegrationService,
  MSFAARequestService,
  MSFAAResponseService,
  SINValidationIntegrationService,
  SINValidationProcessingService,
} from "@sims/integrations/esdc-integration";
import { CRAIntegrationModule } from "@sims/integrations/cra-integration/cra-integration.module";
import { StudentAssessmentService } from "./services";
import { SINValidationService } from "@sims/services/sin-validation/sin-validation.service";
import { StudentService } from "@sims/services/student/student.service";
import { SFASIntegrationModule } from "@sims/integrations/sfas-integration";
import { ATBCIntegrationModule } from "@sims/integrations/atbc-integration";

@Module({
  imports: [
    DatabaseModule,
    QueueModule,
    ZeebeModule.forRoot(),
    IER12IntegrationModule,
    NotificationsModule,
    SystemUserModule,
    CRAIntegrationModule,
    SFASIntegrationModule,
    ATBCIntegrationModule,
  ],
  providers: [
    StartApplicationAssessmentProcessor,
    CancelApplicationAssessmentProcessor,
    WorkflowClientService,
    IER12IntegrationScheduler,
    IER12IntegrationService,
    ProcessNotificationScheduler,
    SFASIntegrationScheduler,
    ATBCResponseIntegrationScheduler,
    StudentAssessmentService,
    StudentsAssessmentService,
    SshService,
    QueueService,
    CRAResponseIntegrationScheduler,
    CRAProcessIntegrationScheduler,
    SequenceControlService,
    WorkflowClientService,
    SINValidationProcessIntegrationScheduler,
    SINValidationProcessingService,
    SystemUsersService,
    SINValidationService,
    StudentService,
    SINValidationIntegrationService,
    SINValidationRequestIntegrationScheduler,
    FullTimeMSFAAProcessIntegrationScheduler,
    MSFAARequestService,
    MSFAANumberService,
    MSFAAIntegrationService,
    PartTimeMSFAAProcessIntegrationScheduler,
    PartTimeECertProcessIntegrationScheduler,
    ECertFileHandler,
    DisbursementSchedulerService,
    IntegrationDisbursementSchedulerService,
    DisbursementScheduleErrorsService,
    ECertFullTimeIntegrationService,
    ECertPartTimeIntegrationService,
    IntegrationStudentRestrictionService,
    ECertFullTimeFileHeader,
    ECertFullTimeFileFooter,
    ECertPartTimeFileHeader,
    ECertPartTimeFileFooter,
    FullTimeECertProcessIntegrationScheduler,
    FullTimeECertFeedbackIntegrationScheduler,
    PartTimeECertFeedbackIntegrationScheduler,
    FullTimeDisbursementReceiptsFileIntegrationScheduler,
    DisbursementReceiptProcessingService,
    DisbursementReceiptIntegrationService,
    IntegrationDisbursementReceiptService,
    FINProcessProvincialDailyDisbursementsIntegrationScheduler,
    DisbursementReceiptRequestService,
    ReportService,
    FederalRestrictionsIntegrationScheduler,
    FedRestrictionProcessingService,
    IntegrationRestrictionService,
    FederalRestrictionService,
    FedRestrictionIntegrationService,
    FullTimeMSFAAProcessResponseIntegrationScheduler,
    PartTimeMSFAAProcessResponseIntegrationScheduler,
    MSFAAResponseService,
  ],
  exports: [QueueService],
})
export class QueueConsumersModule {}
