{{- $secretExists := (lookup "v1" "Secret" $.Release.Namespace "pgbackrest-s3" ) }}
{{- if not $secretExists }}
# This secret allows crunchyDb (pgbackrest) to connect to an S3 host for saving backups.
apiVersion: v1
kind: Secret
metadata:
  name: pgbackrest-s3
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  s3.conf: |
      [global]
      repo2-s3-key={{ .Values.pgBackRest.s3.s3Key }}
      repo2-s3-key-secret={{ .Values.pgBackRest.s3.s3KeySecret }}
{{- end }}