import {
  ApplicationStatus,
  AssessmentTriggerType,
  COEStatus,
  DisbursementScheduleStatus,
  DisbursementValueType,
  FormYesNoOptions,
  OfferingIntensity,
  RelationshipStatus,
} from "@sims/sims-db";
import { IER12TestInputData } from "./ier12-integration.scheduler.models";

export const SINGLE_INDEPENDENT_WITH_NO_DEPENDENTS_STUDENT: IER12TestInputData =
  {
    student: {
      lastName: "Doe",
      firstName: "John",
      birthDate: new Date("1998-01-13"),
      sin: "242963189",
      addressInfo: {
        addressLine1: "Address Line 1",
        addressLine2: "Address Line 2",
        provinceState: "BC",
        city: "Victoria",
        postalCode: "Z1Z1Z1",
      },
    },
    application: {
      applicationNumber: "9879879879",
      studentNumber: "12345678",
      relationshipStatus: RelationshipStatus.Single,
      submittedDate: new Date("2023-10-20"),
      status: ApplicationStatus.Completed,
      statusDate: new Date("2023-10-21"),
      programYear: "2023-2024",
    },
    assessment: {
      triggerType: AssessmentTriggerType.OfferingChange,
      assessmentDate: new Date("2023-10-22"),
      workflowData: {
        studentData: {
          dependantStatus: "independant",
          relationshipStatus: RelationshipStatus.Single,
          livingWithParents: FormYesNoOptions.No,
          numberOfParents: undefined,
        },
        calculatedData: {
          parentalAssets: 654,
          studentMaritalStatusCode: "SI",
          totalEligibleDependents: undefined,
          familySize: 1,
          parentalAssetContribution: undefined,
          parentalContribution: undefined,
          parentDiscretionaryIncome: undefined,
          dependantTotalMSOLAllowance: undefined,
          studentMSOLAllowance: 7777,
          totalChildCareCost: undefined,
          totalNonEducationalCost: 22,
          dependantChildQuantity: undefined,
          dependantChildInDaycareQuantity: undefined,
          dependantInfantQuantity: undefined,
          dependantDeclaredOnTaxesQuantity: undefined,
          dependantPostSecondaryQuantity: undefined,
          partnerStudentStudyWeeks: undefined,
        },
      },
      assessmentData: {
        studentTotalFederalContribution: 9639,
        studentTotalProvincialContribution: 2321,
        parentAssessedContribution: 11,
        partnerAssessedContribution: 22,
        livingAllowance: 33,
        alimonyOrChildSupport: 44,
        totalAssessedCost: 55,
        totalAssessmentNeed: 66,
        weeks: 18,
      },
      disbursements: [
        {
          coeStatus: COEStatus.completed,
          disbursementScheduleStatus: DisbursementScheduleStatus.Pending,
          disbursementDate: "2023-01-23",
          updatedAt: new Date("2023-01-24"),
          dateSent: undefined,
          disbursementValues: [
            {
              valueType: DisbursementValueType.BCLoan,
              valueCode: "CSLF",
              valueAmount: 10998,
            },
            {
              valueType: DisbursementValueType.CanadaGrant,
              valueCode: "CSGP",
              valueAmount: 4000,
            },
          ],
        },
      ],
    },
    educationProgram: {
      name: "Program",
      description: "Program description",
      credentialType: "undergraduateCertificate",
      fieldOfStudyCode: 1,
      cipCode: "12.1234",
      nocCode: "1234",
      sabcCode: "ADR2",
      institutionProgramCode: undefined,
      completionYears: "5YearsOrMore",
      offering: {
        yearOfStudy: 5,
        studyStartDate: new Date("2023-06-01"),
        studyEndDate: new Date("2023-12-31"),
        actualTuitionCosts: 3333,
        programRelatedCosts: 4444,
        mandatoryFees: 5555,
        exceptionalExpenses: 6666,
        offeringIntensity: OfferingIntensity.fullTime,
      },
    },
  };
