apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-creds
labels:
  app: ${NAME}
  template: ${NAME}-creds
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-creds
    stringData:
      clustermode: ${CLUSTER_ENABLED}
      password: ${REDIS_PASSWORD}
      redis.conf: |
        cluster-enabled ${CLUSTER_ENABLED}
        cluster-require-full-coverage no
        cluster-node-timeout ${CLUSTER_NODE_TIMEOUT}
        cluster-config-file /data/nodes.conf
        cluster-migration-barrier 1
        masterauth ${REDIS_PASSWORD}
        masteruser default
        appendonly ${APPEND_ONLY}
        appendfsync ${APPEND_ONLY_FSYNC}
        protected-mode no
        requirepass ${REDIS_PASSWORD}
    type: Opaque
parameters:
  - name: NAME
    description: The name of the application for labelling all artifacts.
    displayName: Application Name
    required: true
    value: redis
  - name: APPEND_ONLY
    description: The file format mode that Redis will save in (no for RDB, yes for AOF)
    displayName: Redis Persistence Mode
    required: true
    value: "yes"
  - name: APPEND_ONLY_FSYNC
    description: The fsync policy of AOF(Append only file).
    displayName: Redis
    required: true
    value: always
  - name: CLUSTER_ENABLED
    description: The file format mode that Redis will save in (no for RDB, yes for AOF)
    displayName: Redis Persistence Mode
    required: true
    value: "yes"
  - name: CLUSTER_NODE_TIMEOUT
    description: Cluster node timeout.
    displayName: Cluster node timeout in milliseconds.
    required: true
    value: "15000"
  - name: REDIS_PASSWORD
    description: Redis password
    displayName: Redis password
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
