apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: api-deploy-pre-req
labels:
  project: ${PROJECT}
  service: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-creds
    stringData:
      bceid-web-service_online_service_id: ${BCeID_WEB_SERVICE_ONLINE_SERVICE_ID}
      bceid-web-service_requester_user_guid: ${BCeID_WEB_SERVICE_REQUESTER_USER_GUID}
      bceid-web-service_auth_user_name: ${BCeID_WEB_SERVICE_AUTH_USER_NAME}
      bceid-web-service_auth_user_password: ${REQ_BCeID_WEB_SERVICE_AUTH_USER_PASSWORD}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    value: api
  - name: PROJECT
    value: sims
  - name: BCeID_WEB_SERVICE_ONLINE_SERVICE_ID
    displayName: BCeID Web Service Online Service ID
    description: |
      The Online Service Identifier is a unique key given to each Online Service.
      When you create an Online Service this identifier is generated.
      This key will be used in conjunction with the service account to
      determine authorizations to access each method. The expectation is to
      receive this as a configurable parameter.
    required: true
  - name: BCeID_WEB_SERVICE_REQUESTER_USER_GUID
    displayName: BCeID Web Service Requester User Guid
    description: |
      The user GUID of the user that will be executing the Web Services calls.
      This user represents the user from Ministry LDAP and not the user from
      Keyclock and/or BCeID.
    required: true
  - name: BCeID_WEB_SERVICE_AUTH_USER_NAME
    displayName: BCeID Web Service Authentication User Name
    description: |
      User used to authenticate to the BCeID Web Service.
      The user name is expected to be in the format Domain\UserName
      (e.g. IDIR\UserName).
    required: true
  - name: BCeID_WEB_SERVICE_AUTH_USER_PASSWORD
    displayName: BCeID Web Service Authentication User Password
    required: true
    description: |
      Password used to authenticate to the BCeID Web Service.
