apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: api-pre-req
labels:
  project: ${PROJECT_NAME}
  service: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${PROJECT_NAME}-${NAME}-creds
    stringData:
      bceid-web-service-online-service-id: ${BCeID_WEB_SERVICE_ONLINE_SERVICE_ID}
      bceid-web-service-requester-user-guid: ${BCeID_WEB_SERVICE_REQUESTER_USER_GUID}
      bceid-web-service-auth-user-name: ${BCeID_WEB_SERVICE_AUTH_USER_NAME}
      bceid-web-service-auth-user-password: ${BCeID_WEB_SERVICE_AUTH_USER_PASSWORD}
      workflow-sa-user-name: ${WORKFLOW_SA_USER_NAME}
      workflow-sa-password: ${WORKFLOW_SA_PASSWORD}
      forms-sa-user-name: ${FORMS_SA_USER_NAME}
      forms-sa-password: ${FORMS_SA_PASSWORD}
      sims-api-client-id: ${SIMS_API_CLIENT_ID}
      sims-api-client-secret: ${SIMS_API_CLIENT_SECRET}
      cra-request-folder: ${CRA_REQUEST_FOLDER}
      cra-response-folder: ${CRA_RESPONSE_FOLDER}
      cra-program-area-code: ${CRA_PROGRAM_AREA_CODE}
      cra-environment-code: ${CRA_ENVIRONMENT_CODE}
      msfaa-request-folder: ${MSFAA_REQUEST_FOLDER}
      msfaa-response-folder: ${MSFAA_RESPONSE_FOLDER}
      msfaa-province-code: ${MSFAA_PROVINCE_CODE}
      sfas-receive-folder: ${SFAS_RECEIVE_FOLDER}
      atbc-username: ${ATBC_USERNAME}
      atbc-password: ${ATBC_PASSWORD}
      atbc-app: ${ATBC_APP}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    value: api
  - name: PROJECT_NAME
    value: sims
  - name: BCeID_WEB_SERVICE_ONLINE_SERVICE_ID
    displayName: BCeID Web Service Online Service ID
    description: |
      The Online Service Identifier is a unique key given to each Online Service.
      When you create an Online Service this identifier is generated.
      This key will be used in conjunction with the service account to
      determine authorizations to access each method.
      Linked to the IDIR by BCeID (IDIM team-CITZ Services), ISA required.
    required: true
  - name: BCeID_WEB_SERVICE_REQUESTER_USER_GUID
    displayName: BCeID Web Service Requester User Guid
    description: |
      The user GUID of the user that will be executing the Web Services calls.
      This user represents the user from Ministry LDAP and not the user from
      Keyclock and/or BCeID.
    required: true
  - name: BCeID_WEB_SERVICE_AUTH_USER_NAME
    displayName: BCeID Web Service Authentication User Name
    description: |
      User used to authenticate to the BCeID Web Service.
      The user name is expected to be in the format Domain\UserName
      (e.g. IDIR\UserName).
    required: true
  - name: BCeID_WEB_SERVICE_AUTH_USER_PASSWORD
    displayName: BCeID Web Service Authentication User Password
    required: true
    description: |
      Password used to authenticate to the BCeID Web Service.
  - name: WORKFLOW_SA_USER_NAME
    displayName: Service Account Username (from Keycloak) for workflow engine (Camunda)
    required: true
    description: |
      Service Account Username (from Keycloak) for workflow engine (Camunda).
  - name: WORKFLOW_SA_PASSWORD
    displayName: Service Account password (from Keycloak) for workflow engine (Camunda)
    required: true
    description: |
      Service Account password (from Keycloak) for workflow engine (Camunda).
  - name: FORMS_SA_USER_NAME
    displayName: Service Account Username for formio
    required: true
    description: |
      Service Account Username for formio.
  - name: FORMS_SA_PASSWORD
    displayName: Service Account Password for formio
    required: true
    description: |
      Service Account Password for formio.
  - name: SIMS_API_CLIENT_ID
    displayName: Keycloak Client ID
    required: true
    description: |
      Keycloak Client ID to allow SIMS Api to retrieve the token.
  - name: SIMS_API_CLIENT_SECRET
    displayName: Keycloak Client Secret
    required: true
    description: |
      Keycloak Client Secret to allow SIMS Api to retrieve the token.
  - name: CRA_REQUEST_FOLDER
    displayName: CRA Request Folder
    required: true
    description: |
      CRA folder on ZONE B network server to upload files.
  - name: CRA_RESPONSE_FOLDER
    displayName: CRA Response Folder
    required: true
    description: |
      CRA folder on ZONE B network server to read files.
  - name: CRA_PROGRAM_AREA_CODE
    displayName: CRA Program Area Code
    required: true
    description: |
      Program are code provided by CRA (4 letters).
  - name: CRA_ENVIRONMENT_CODE
    displayName: CRA Environment Code
    required: true
    description: |
      CRA environment identifier (A=Test, P=Production).
  - name: ATBC_USERNAME
    displayName: ATBC username
    required: true
    description: |
      ATBC username to get access token.
  - name: ATBC_PASSWORD
    displayName: ATBC password
    required: true
    description: |
      ATBC password to get access token.
  - name: ATBC_APP
    displayName: ATBC App name
    required: true
    description: |
      ATBC App name to get access token.
  - name: MSFAA_REQUEST_FOLDER
    displayName: MSFAA request folder
    required: true
    description: |
      MSFAA folder on ZONE B network server to upload files.
  - name: MSFAA_RESPONSE_FOLDER
    displayName: MSFAA response folder
    required: true
    description: |
      MSFAA folder on ZONE B network server to receive files.
  - name: MSFAA_PROVINCE_CODE
    displayName: MSFAA province code
    required: true
    description: |
      MSFAA province code
  - name: SFAS_RECEIVE_FOLDER
    displayName: SFAS receive folder
    required: true
    description: |
      Folder on the SFTP where SFAS integration files will be placed.
