apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: forms
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      DEBUG: formio:*
      FORMIO_ROOT_EMAIL: "${FORMIO_ROOT_EMAIL}"
      FORMIO_ROOT_PASSWORD: "${FORMIO_ROOT_PASSWORD}"
      MONGODB_URI: "${MONGODB_URI}"
      NODE_CONFIG: '{"mongo": "${MONGODB_URI}"}'
      FORMS_URL: "https://${FORMS_URL}"
    type: Opaque

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      replicas: "${{REPLICAS}}"
      selector:
        matchLabels:
          app: ${NAME}
      strategy:
        type: RollingUpdate
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
      template:
        metadata:
          labels:
            app: ${NAME}
        spec:
          containers:
            - env:
                - name: DEBUG
                  valueFrom:
                    secretKeyRef:
                      key: DEBUG
                      name: ${NAME}
                - name: NODE_CONFIG
                  valueFrom:
                    secretKeyRef:
                      key: NODE_CONFIG
                      name: ${NAME}
                - name: ROOT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      key: FORMIO_ROOT_EMAIL
                      name: ${NAME}
                - name: ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: FORMIO_ROOT_PASSWORD
                      name: ${NAME}
                - name: FORMIO_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      key: FORMS_URL
                      name: ${NAME}
              image: ${IMAGE_REGISTRY}/${TOOLS_NAMESPACE}/${IMAGE_STREAM_TAG}
              name: ${NAME}
              ports:
                - containerPort: 3001
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  memory: "${MEMORY_LIMIT}"
              livenessProbe:
                tcpSocket:
                  path: "/ops/healthz"
                  port: 3001
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  path: "/ops/readyz"
                  port: 3001
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
              stdin: true
              tty: true
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      test: false
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      ports:
        - name: "3001"
          port: 3001
          targetPort: 3001
      selector:
        app: ${NAME}
    status:
      loadBalancer: {}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}-route
      annotations:
        haproxy.router.openshift.io/balance: leastconn
        haproxy.router.openshift.io/disable_cookies: "true"
        haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
        haproxy.router.openshift.io/timeout: 30s
    spec:
      host: ${FORMS_URL}
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      port:
        targetPort: "3001"
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
        certificate: |
          -----BEGIN CERTIFICATE-----
          ${TLS_CERTIFICATE}
          -----END CERTIFICATE-----
        key: |
          -----BEGIN PRIVATE KEY-----
          ${TLS_KEY}
          -----END PRIVATE KEY-----
        caCertificate: |
          -----BEGIN CERTIFICATE-----
          ${TLS_CA_CERTIFICATE}
          -----END CERTIFICATE-----
      wildcardPolicy: None
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}-hpa
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ${NAME}
      minReplicas: "${{REPLICAS}}"
      maxReplicas: 6
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 80
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: ${NAME}-pdb
    spec:
      selector:
        matchLabels:
          app: ${NAME}
      maxUnavailable: 1
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: forms
  - name: TOOLS_NAMESPACE
    displayName: Image TOOLS_NAMESPACE
    required: true
    description:
      The TOOLS_NAMESPACE of the OpenShift project containing the imagestream for
      the application.
  - name: MONGODB_URI
    description: MONGODB_URI
    required: true
  - name: FORMIO_ROOT_EMAIL
    description: FORMIO_ROOT_EMAIL
    required: true
  - name: FORMIO_ROOT_PASSWORD
    description: FORMIO_ROOT_PASSWORD
    required: true
  - name: FORMS_URL
    displayName: FORMS_URL
    required: true
    description: Forms URL
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: IMAGE_STREAM_TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: latest
  - name: REPLICAS
    required: true
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
  - name: TLS_CERTIFICATE
    required: true
  - name: TLS_KEY
    required: true
  - name: TLS_CA_CERTIFICATE
    required: true
