apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Template for running a job that performs a database migrations"
labels:
  project: ${PROJECT}
  service: ${SERVICE_NAME}
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${JOB_NAME}
    spec:
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}} # The maximum duration the job can run.
      backoffLimit: 5 # The number of retries for a job.
      template:
        metadata:
          name: ${JOB_NAME}
        spec:
          containers:
            - name: db-migrations-container
              image: ${IMAGE_REGISTRY}/${BUILD_NAMESPACE}/${IMAGE_STREAM_TAG}
              env:
                - name: VERSION
                  value: ${BUILD_TAG}
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_SERVICE_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_USERNAME_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_PASSWORD_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      key: ${SIMS_DB_NAME}
                      name: ${MIGRATIONS_SECRET_NAME}
                - name: FORMS_SA_USER_NAME
                  valueFrom:
                    secretKeyRef:
                      key: ${FORMIO_ROOT_EMAIL_NAME_KEY}
                      name: ${FORMS_SECRET_NAME}
                - name: FORMS_SA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ${FORMIO_ROOT_PASSWORD_NAME_KEY}
                      name: ${FORMS_SECRET_NAME}
                - name: FORMS_URL
                  value: "${FORMS_URL}"
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
          restartPolicy: OnFailure
parameters:
  - name: NAME
    required: true
  - name: BUILD_TAG
    value: "0"
  - name: PROJECT
    value: sims
  - name: SERVICE_NAME
    value: db-migrations
  - name: MIGRATIONS_SECRET_NAME
    required: true
  - name: SIMS_DB_NAME
    value: sims-db-name
  - name: JOB_NAME
    description: database.migrations
    required: true
    value: db-migrations-job
  - name: IMAGE_STREAM_TAG
    required: true
  - name: BUILD_NAMESPACE
    required: true
  - name: FORMS_URL
    required: true
  - name: ACTIVE_DEADLINE_SECONDS
    required: true
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: DB_SERVICE_KEY
    value: pgbouncer-host
  - name: DB_SECRET_NAME
    value: simsdb-pguser-non-super-user
  - name: DB_USERNAME_KEY
    value: user
  - name: DB_PASSWORD_KEY
    value: password
  - name: FORMS_SECRET_NAME
    value: dev-forms
  - name: FORMIO_ROOT_EMAIL_NAME_KEY
    value: FORMIO_ROOT_EMAIL
  - name: FORMIO_ROOT_PASSWORD_NAME_KEY
    value: FORMIO_ROOT_PASSWORD
  - name: FORMS_URL_NAME_KEY
    value: FORMS_URL
  - name: MEMORY_LIMIT
    value: "500M"
  - name: CPU_REQUEST
    value: "0.5"
  - name: MEMORY_REQUEST
    value: "500M"
