apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Template for running a job that performs a database migrations"
labels:
  project: ${PROJECT}
  service: ${SERVICE_NAME}
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${JOB_NAME}
      labels:
        app.kubernetes.io/part-of: sims-packages-group
    spec:
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}} # The maximum duration the job can run.
      backoffLimit: 5 # The number of retries for a job.
      template:
        metadata:
          name: ${JOB_NAME}
        spec:
          containers:
            - name: db-migrations-container
              image: ${IMAGE_REGISTRY}/${BUILD_NAMESPACE}/${IMAGE_STREAM_TAG}
              command: ["/bin/sh", "-c"]
              args: ["${MIGRATION_COMMAND}"]
              imagePullPolicy: Always
              env:
                - name: CAMUNDA_TOKEN_DISK_CACHE_DISABLE
                  value: ${CAMUNDA_TOKEN_DISK_CACHE_DISABLE}
                - name: VERSION
                  value: ${BUILD_TAG}
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_SERVICE_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_USERNAME_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_PASSWORD_KEY}
                      name: ${DB_SECRET_NAME}
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      key: ${SIMS_DB_NAME}
                      name: ${MIGRATIONS_SECRET_NAME}
                - name: FORMS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: ${FORMIO_API_KEY_NAME_KEY}
                      name: ${FORMS_SECRET_NAME}
                      optional: true
                - name: FORMS_URL
                  value: "${FORMS_URL}"
                - name: ZEEBE_GRPC_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      key: ${ZEEBE_GRPC_ADDRESS_KEY}
                      name: ${MIGRATIONS_SECRET_NAME}
                      optional: true
                - name: ZEEBE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: ${ZEEBE_CLIENT_ID_KEY}
                      name: ${MIGRATIONS_SECRET_NAME}
                      optional: true
                - name: ZEEBE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: ${ZEEBE_CLIENT_SECRET_KEY}
                      name: ${MIGRATIONS_SECRET_NAME}
                      optional: true
                - name: CAMUNDA_OAUTH_URL
                  valueFrom:
                    secretKeyRef:
                      key: ${CAMUNDA_OAUTH_URL_KEY}
                      name: ${MIGRATIONS_SECRET_NAME}
                      optional: true
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
          restartPolicy: Never
parameters:
  - name: NAME
    required: true
  - name: BUILD_TAG
    value: "0"
  - name: PROJECT
    value: sims
  - name: SERVICE_NAME
    value: db-migrations
  - name: MIGRATIONS_SECRET_NAME
    required: true
  - name: SIMS_DB_NAME
    value: sims-db-name
  - name: JOB_NAME
    description: database.migrations
    required: true
    value: db-migrations-job
  - name: IMAGE_STREAM_TAG
    required: true
  - name: BUILD_NAMESPACE
    required: true
  - name: ACTIVE_DEADLINE_SECONDS
    required: true
  - name: MIGRATION_COMMAND
    required: true
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: DB_SERVICE_KEY
    value: pgbouncer-host
  - name: DB_SECRET_NAME
    value: simsdb-pguser-non-super-user
  - name: DB_USERNAME_KEY
    value: user
  - name: DB_PASSWORD_KEY
    value: password
  - name: FORMS_URL
    required: true
  - name: FORMS_SECRET_NAME
    required: true
  - name: FORMIO_API_KEY_NAME_KEY
    value: FORMIO_API_KEY
  - name: FORMS_URL_NAME_KEY
    value: FORMS_URL
  - name: ZEEBE_GRPC_ADDRESS_KEY
    value: zeebe-address
  - name: ZEEBE_CLIENT_ID_KEY
    value: zeebe-client-id
  - name: ZEEBE_CLIENT_SECRET_KEY
    value: zeebe-client-secret
  - name: CAMUNDA_OAUTH_URL_KEY
    value: camunda-oauth-url
  - name: CAMUNDA_TOKEN_DISK_CACHE_DISABLE
    value: "true"
  - name: MEMORY_LIMIT
    value: "500M"
  - name: CPU_REQUEST
    value: "0.5"
  - name: MEMORY_REQUEST
    value: "500M"
