apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: patroni-pre-req
labels:
  project: ${PROJECT}
  service: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-creds
    stringData:
      replication-username: ${PATRONI_REPLICATION_USERNAME}
      replication-password: ${PATRONI_REPLICATION_PASSWORD}
      superuser-username: ${PATRONI_SUPERUSER_USERNAME}
      superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
      database-name: ${APP_DB_NAME}
      database-user: app_api_${APP_DB_USERNAME}
      database-password: ${APP_DB_PASSWORD}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ${NAME}
    rules:
      - apiGroups:
          - ""
        resources:
          - services
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - endpoints
        verbs:
          - get
          - patch
          - update
          - create
          - list
          - watch
          - delete
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - patch
          - update
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ${NAME}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    value: patroni
  - name: PROJECT
    value: sims
  - name: PATRONI_SUPERUSER_USERNAME
    description: |
      Username of the superuser account for initialization.
    displayName: Superuser Username
    value: postgres
  - name: PATRONI_SUPERUSER_PASSWORD
    description: |
      Password of the superuser account for initialization.
    displayName: Superuser Password
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: PATRONI_REPLICATION_USERNAME
    description: |
      Username of the replication account for initialization.
    displayName: Replication Username
    value: replication
  - name: PATRONI_REPLICATION_PASSWORD
    description: Password of the replication account for initialization.
    displayName: Replication Password
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: APP_DB_USERNAME
    generate: expression
    from: "[a-zA-Z0-9]{8}"
  - name: APP_DB_NAME
    value: SIMSDB
  - name: APP_DB_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
