apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${SECRET_NAME}-template
labels:
  project: ${PROJECT_NAME}
  service: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
    stringData:
      API_PORT: ${API_PORT}
      ATBC_APP: ${ATBC_APP}
      ATBC_ENDPOINT: ${ATBC_ENDPOINT}
      ATBC_LOGIN_ENDPOINT: ${ATBC_LOGIN_ENDPOINT}
      ATBC_PASSWORD: ${ATBC_PASSWORD}
      ATBC_USERNAME: ${ATBC_USERNAME}
      BCEID_WEB_SERVICE_AUTH_USER_NAME: ${BCEID_WEB_SERVICE_AUTH_USER_NAME}
      BCEID_WEB_SERVICE_AUTH_USER_PASSWORD: ${BCEID_WEB_SERVICE_AUTH_USER_PASSWORD}
      BCEID_WEB_SERVICE_ONLINE_SERVICE_ID: ${BCEID_WEB_SERVICE_ONLINE_SERVICE_ID}
      BCEID_WEB_SERVICE_REQUESTER_USER_GUID: ${BCEID_WEB_SERVICE_REQUESTER_USER_GUID}
      BCEID_WEB_SERVICE_WSDL: ${BCEID_WEB_SERVICE_WSDL}
      BYPASS_APPLICATION_SUBMIT_VALIDATIONS: ${BYPASS_APPLICATION_SUBMIT_VALIDATIONS}
      BYPASS_CRA_INCOME_VERIFICATION: ${BYPASS_CRA_INCOME_VERIFICATION}
      CAMUNDA_OAUTH_URL: ${CAMUNDA_OAUTH_URL}
      CAS_BASE_URL: ${CAS_BASE_URL}
      CAS_CLIENT_ID: ${CAS_CLIENT_ID}
      CAS_CLIENT_SECRET: ${CAS_CLIENT_SECRET}
      CRA_ENVIRONMENT_CODE: ${CRA_ENVIRONMENT_CODE}
      CRA_PROGRAM_AREA_CODE: ${CRA_PROGRAM_AREA_CODE}
      CRA_REQUEST_FOLDER: ${CRA_REQUEST_FOLDER}
      CRA_RESPONSE_FOLDER: ${CRA_RESPONSE_FOLDER}
      ESDC_ENVIRONMENT_CODE: ${ESDC_ENVIRONMENT_CODE}
      ESDC_REQUEST_FOLDER: ${ESDC_REQUEST_FOLDER}
      ESDC_RESPONSE_FOLDER: ${ESDC_RESPONSE_FOLDER}
      FORMS_DB_PASSWORD: ${FORMS_DB_PASSWORD}
      FORMS_DB_USER: ${FORMS_DB_USER}
      FORMS_SA_PASSWORD: ${FORMS_SA_PASSWORD}
      FORMS_SA_USER_NAME: ${FORMS_SA_USER_NAME}
      FORMS_SECRET_NAME: ${FORMS_SECRET_NAME}
      GC_NOTIFY_API_KEY: ${GC_NOTIFY_API_KEY}
      GC_NOTIFY_URL: ${GC_NOTIFY_URL}
      HOST_PREFIX: ${HOST_PREFIX}
      INSTITUTION_REQUEST_FOLDER: ${INSTITUTION_REQUEST_FOLDER}
      INSTITUTION_RESPONSE_FOLDER: ${INSTITUTION_RESPONSE_FOLDER}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      MONGODB_URI: ${MONGODB_URI}
      OPENSHIFT_ENV_NAMESPACE: ${OPENSHIFT_ENV_NAMESPACE}
      OPENSHIFT_SIMS_CREDS_NAME: ${OPENSHIFT_SIMS_CREDS_NAME}
      QUEUE_DASHBOARD_TOKEN_SECRET: ${QUEUE_DASHBOARD_TOKEN_SECRET}
      QUEUE_PREFIX: ${QUEUE_PREFIX}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_DEFAULT_BUCKET: ${S3_DEFAULT_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      SFAS_RECEIVE_FOLDER: ${SFAS_RECEIVE_FOLDER}
      SIMS_DB_NAME: ${SIMS_DB_NAME}
      SITE_MINDER_LOGOUT_URL: ${SITE_MINDER_LOGOUT_URL}
      WEB_PORT: ${WEB_PORT}
      ZEEBE_ADDRESS: ${ZEEBE_ADDRESS}
      ZEEBE_CLIENT_ID: ${ZEEBE_CLIENT_ID}
      ZEEBE_CLIENT_SECRET: ${ZEEBE_CLIENT_SECRET}
      ZEEBE_GRPC_WORKER_LONGPOLL_SECONDS: ${ZEEBE_GRPC_WORKER_LONGPOLL_SECONDS}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    required: true
  - name: SECRET_NAME
    description: |
      The name of the secret to be linked.
    displayName: Secret name
    required: true
  - name: PROJECT_NAME
    value: sims
  - name: API_PORT
    required: true
  - name: ATBC_APP
    required: true
  - name: ATBC_ENDPOINT
    required: true
  - name: ATBC_LOGIN_ENDPOINT
    required: true
  - name: ATBC_PASSWORD
    required: true
  - name: ATBC_USERNAME
    required: true
  - name: BCEID_WEB_SERVICE_AUTH_USER_NAME
    required: true
  - name: BCEID_WEB_SERVICE_AUTH_USER_PASSWORD
    required: true
  - name: BCEID_WEB_SERVICE_ONLINE_SERVICE_ID
    required: true
  - name: BCEID_WEB_SERVICE_REQUESTER_USER_GUID
    required: true
  - name: BCEID_WEB_SERVICE_WSDL
    required: true
  - name: BYPASS_APPLICATION_SUBMIT_VALIDATIONS
    required: true
  - name: BYPASS_CRA_INCOME_VERIFICATION
    required: true
  - name: CAMUNDA_OAUTH_URL
    required: true
  - name: CAS_BASE_URL
    required: true
  - name: CAS_CLIENT_ID
    required: true
  - name: CAS_CLIENT_SECRET
    required: true
  - name: CRA_ENVIRONMENT_CODE
    required: true
  - name: CRA_PROGRAM_AREA_CODE
    required: true
  - name: CRA_REQUEST_FOLDER
    required: true
  - name: CRA_RESPONSE_FOLDER
    required: true
  - name: ESDC_ENVIRONMENT_CODE
    required: true
  - name: ESDC_REQUEST_FOLDER
    required: true
  - name: ESDC_RESPONSE_FOLDER
    required: true
  - name: FORMS_DB_PASSWORD
    required: true
  - name: FORMS_DB_USER
    required: true
  - name: FORMS_SA_PASSWORD
    required: true
  - name: FORMS_SA_USER_NAME
    required: true
  - name: FORMS_SECRET_NAME
    required: true
  - name: GC_NOTIFY_API_KEY
    required: true
  - name: GC_NOTIFY_URL
    required: true
  - name: HOST_PREFIX
    required: true
  - name: INSTITUTION_REQUEST_FOLDER
    required: true
  - name: INSTITUTION_RESPONSE_FOLDER
    required: true
  - name: KEYCLOAK_AUTH_URL
    required: true
  - name: MONGODB_URI
    required: true
  - name: QUEUE_DASHBOARD_TOKEN_SECRET
    required: true
  - name: QUEUE_PREFIX
    required: true
  - name: S3_ACCESS_KEY_ID
    required: true
  - name: S3_DEFAULT_BUCKET
    required: true
  - name: S3_ENDPOINT
    required: true
  - name: S3_REGION
    required: true
  - name: S3_SECRET_ACCESS_KEY
    required: true
  - name: SFAS_RECEIVE_FOLDER
    required: true
  - name: SIMS_DB_NAME
    required: true
  - name: SITE_MINDER_LOGOUT_URL
    required: true
  - name: WEB_PORT
    required: true
  - name: ZEEBE_ADDRESS
    required: true
  - name: ZEEBE_CLIENT_ID
    required: true
  - name: ZEEBE_CLIENT_SECRET
    required: true
  - name: ZEEBE_GRPC_WORKER_LONGPOLL_SECONDS
    required: true
  - name: OPENSHIFT_ENV_NAMESPACE
    required: true
  - name: OPENSHIFT_SIMS_CREDS_NAME
    required: true
