apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
labels:
  project: ${PROJECT}
  service: ${SERVICE_NAME}
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: "${{REPLICAS}}"
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: ${NODE_ENV}
                - name: PORT
                  value: "${PORT}"
              image: ${IMAGE_REGISTRY}/${BUILD_NAMESPACE}/${IMAGE_STREAM_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: "${{PORT}}"
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /
                  port: "${{PORT}}"
                initialDelaySeconds: 20
                periodSeconds: 30
                timeoutSeconds: 15
              livenessProbe:
                failureThreshold: 10
                httpGet:
                  path: /
                  port: "${{PORT}}"
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 30
                timeoutSeconds: 15
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
        - name: http
          port: 80
          targetPort: ${{PORT}}
      selector:
        deploymentconfig: ${NAME}
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      host: ${HOST_NAME}
      path: ${PATH}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
parameters:
  - name: NAME
    required: true
  - name: PROJECT 
    value: sims
  - name: SERVICE_NAME
    value: web
  - name: CPU_LIMIT
    value: "0.5"
  - name: MEMORY_LIMIT
    value: "256M"
  - name: CPU_REQUEST
    value: "0.1"
  - name: MEMORY_REQUEST
    value: "256M"
  - name: REPLICAS
    value: "2"
  - name: PORT
    value: "7070"
  - name: IMAGE_STREAM_TAG
    required: true  
  - name: BUILD_NAMESPACE
    required: true
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: PATH
    value: "/"
  - name: NODE_ENV
    value: "production"
  - name: HOST_NAME
    required: true
