import { OfferingIntensity } from "@sims/sims-db";
import {
  AssessmentConsolidatedData,
  OfferingDeliveryOptions,
  YesNoOptions,
} from "../models/assessment-consolidated-data.model";

export function getFakeAssessmentConsolidatedData(
  offeringIntensity: OfferingIntensity,
  programYear: string,
): AssessmentConsolidatedData {
  return {
    studentDataDependantstatus: "independant",
    programYear,
    programYearStartDate: "2022-08-01",
    studentDataRelationshipStatus: "single",
    studentDataTaxReturnIncome: 35000,
    studentDataWhenDidYouGraduateOrLeaveHighSchool: "2018-02-02",
    studentDataIndigenousStatus: YesNoOptions.No,
    studentDataHasDependents: YesNoOptions.No,
    studentDataLivingWithParents: YesNoOptions.No,
    studentDataYouthInCare: YesNoOptions.No,
    studentPDStatus: false,
    studentTaxYear: 2021,
    programLocation: "BC",
    institutionLocationProvince: "BC",
    institutionType: "BC Public",
    programLength: "1YearToLessThan2Years",
    programCredentialType: "undergraduateDegree",
    offeringIntensity,
    offeringDelivered: OfferingDeliveryOptions.Onsite,
    offeringStudyEndDate: "2023-02-28",
    offeringStudyStartDate: "2022-11-01",
    offeringProgramRelatedCosts: 3333,
    offeringActualTuitionCosts: 333333,
    offeringMandatoryFees: 33,
    offeringExceptionalExpenses: 33,
    offeringWeeks: 17,
    applicationId: null,
    appealsStudentIncomeAppealData: null,
    appealsPartnerIncomeAppealData: null,
    studentDataSelectedLocation: null,
    studentDataSelectedProgram: null,
    studentDataSelectedOffering: null,
    studentDataIsYourSpouseACanadianCitizen: null,
    studentDataParentValidSinNumber: null,
    studentDataNumberOfParents: null,
    studentDataEstimatedSpouseIncome: null,
    studentDataLivingWithPartner: null,
    studentDataCRAReportedIncome: null,
    studentDataDependants: null,
    studentDataGovernmentFundingCosts: null,
    studentDataNongovernmentFundingCosts: null,
    studentDataParentVoluntaryContributionsCosts: null,
    studentDataPartnerStudyWeeks: null,
    studentDataPartnerEmploymentInsurance: null,
    studentDataPartnerFedralProvincialPDReceiptCost: null,
    studentDataParentDependentTable: null,
    studentDataStudentParentNetAssests: null,
    studentDataStudentParentNetContribution: null,
    studentDataPartnerTotalIncomeAssistance: null,
    studentDataVoluntaryContributions: null,
    studentDataScholarshipAmount: null,
    studentDataPleaseProvideAnEstimationOfYourParentsIncome: null,
    studentDataChildSupportAndOrSpousalSupport: null,
    studentDataDaycareCosts11YearsOrUnder: null,
    studentDataDaycareCosts12YearsOrOver: null,
    studentDataLivingathomeRent: null,
    studentDataTransportationCost: null,
    offeringCourseLoad: null, // asessment to-do:probably number from 20-59.
    parent1SupportingUserId: null,
    parent1Contributions: null,
    parent1Ei: null,
    parent1NetAssests: null,
    parent1Tax: null,
    parent1TotalIncome: null,
    parent1DependentTable: [],
    parent1CRAReportedIncome: null,
    parent1CppEmployment: null,
    parent1CppSelfemploymentOther: null,
    parent2SupportingUserId: null,
    parent2Contributions: null,
    parent2CppSelfemploymentOther: null,
    parent2DependentTable: [],
    parent2Ei: null,
    parent2NetAssests: null,
    parent2Tax: null,
    parent2TotalIncome: null,
    parent2CRAReportedIncome: null,
    parent2CppEmployment: null,
    partner1SupportingUserId: null,
    partner1SocialAssistance: null,
    partner1EmploymentInsuranceBenefits: null,
    partner1TotalStudentLoan: null,
    partner1PermanentDisabilityBenefits: null,
    partner1StudentStudyWeeks: null,
    partner1CRAReportedIncome: null,
    partner1TotalIncome: null,
  };
}
