export const ASSESSMENT_ALREADY_IN_PROGRESS = "ASSESSMENT_ALREADY_IN_PROGRESS";
export const ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
export const ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE";
/**
 * An assessment cannot be accepted due to an institution restriction.
 */
export const ASSESSMENT_CANNOT_BE_ACCEPTED_DUE_TO_INSTITUTION_RESTRICTION =
  "ASSESSMENT_CANNOT_BE_ACCEPTED_DUE_TO_INSTITUTION_RESTRICTION";
export const MASKED_MSFAA_NUMBER = "XXXXXXXXXX";
export const MASKED_MONEY_AMOUNT = "XXXXX";
