export const ASSESSMENT_ALREADY_IN_PROGRESS = "ASSESSMENT_ALREADY_IN_PROGRESS";
export const ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
export const ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE";
export const MASKED_MSFAA_NUMBER = "XXXXXXXXXX";
export const MASKED_MONEY_AMOUNT = "XXXXX";
