export const ColumnNames = {
  ID: "id",
  CreateTimestamp: "created_at",
  UpdateTimestamp: "updated_at",
  Creator: "creator",
  Modifier: "modifier",
};

export const TableNames = {
  User: "users",
  Student: "students",
  Institution: "institutions",
  Applications: "applications",
  StudentsFiles: "student_files",
  ApplicationStudentFiles: "application_student_files",
  EducationPrograms: "education_programs",
  EducationProgramsOfferings: "education_programs_offerings",
  ProgramYear: "program_years",
  PIRDeniedReason: "pir_denied_reason",
  MSFAANumbers: "msfaa_numbers",
  COEDeniedReason: "coe_denied_reasons",
  CRAIncomeVerification: "cra_income_verifications",
  SupportingUsers: "supporting_users",
  Restrictions: "restrictions",
  StudentRestrictions: "student_restrictions",
  SFASIndividuals: "sfas_individuals",
  SFASApplications: "sfas_applications",
  SFASRestrictions: "sfas_restrictions",
  DisbursementSchedule: "disbursement_schedules",
  DisbursementValue: "disbursement_values",
  DisbursementFeedbackErrors: "disbursement_feedback_errors",
};
