export const APPLICATION_SUBMISSION_PAYLOAD = {
  data: {
    workflowName: "assessment-gateway",
    selectedLocation: 14,
    mySchoolIsNotListed: false,
    studentNumber: "",
    selectedProgramDesc: {
      id: 211,
      name: "Computer Sciences",
      description: "Computer science description",
      credentialType: "graduateDiploma",
      credentialTypeToDisplay: "Graduate Diploma",
      deliveryMethod: "Onsite",
    },
    selectedOfferingDate: "2023-09-11",
    selectedOfferingEndDate: "2023-11-28",
    maximumAllowedDaysAfterStudyEndDate: 42,
    studyEndDateBeforeToday: false,
    selectedStudyEndDateBeforeToday: false,
    studyPeriodMinDays: 84,
    studyPeriodMaxDays: "365",
    studentGivenNames: "MATT",
    studentDateOfBirth: "Nov 25 1985",
    studentHomeAddress: "123 Humboldt St, Victoria, BC, V9V1V1, canada",
    studentEmail: "simsfive@test.ca",
    studentLastName: "FRANKY",
    studentGender: "man",
    studentPhoneNumber: "7789221234",
    disabilityStatus: "Requested",
    studentInfoConfirmed: true,
    citizenship: "canadianCitizen",
    bcResident: "yes",
    indigenousStatus: "no",
    youthInCare: "no",
    addTrustContactToContactSABC: "no",
    roiInformation: [
      {
        fullNmae: "",
        relationshipToYou: "",
        fullName: "",
        firstName: "",
        lastName: "",
        strongWhatIsYourRelationshipWithThisContactStrong: "",
        strongHowLongDoYouWantToGiveThisPersonAccessToYourStudentAidBcAccountStrong:
          "",
        selectTheDateYouWouldLikeThisPersonsAccessToYourStudentAidBcAccountToExpire:
          "",
      },
    ],
    relationshipStatus: "single",
    hasDependents: "yes",
    showParentInformation: false,
    craConsent: true,
    haveDaycareCosts11YearsOrUnder: "no",
    haveDaycareCosts12YearsOrOver: "no",
    dependantstatus: "independant",
    studentAidBcConsent: true,
    applicationId: "",
    applicationStatus: "",
    selectedLocationName: "Victoria College",
    howWillYouBeAttendingTheProgram: "Full Time",
    myProgramNotListed: {
      programnotListed: false,
    },
    programYearStartDate: "2023-08-01",
    programYearEndDate: "2024-07-31",
    taxReturnIncome: 9999999999,
    outOfHighSchoolFor4Years: "no",
    whenDidYouGraduateOrLeaveHighSchool: "2023-10-03",
    fulltimelabourForce: "no",
    hasSignificantDegreeOfIncome: "no",
    exceptionalExpense: "no",
    childSupport: "no",
    parentvoluntaryContributions: "no",
    governmentFunding: "no",
    nonGovernmentFunding: "no",
    scholarshipsReceived: "no",
    bcIncomeassistanceforDisabilities: "no",
    livingWithParents: "no",
    strongIfYouMustRelocateToADifferentCityToAttendSchoolDoYouWantToProvideACostToBeConsideredStrong:
      "no",
    additionalTransportRequested: "no",
    selectedProgram: 211,
    selectedOffering: 425,
    myStudyPeriodIsntListed: {
      offeringnotListed: false,
    },
    dependants: [
      {
        fullName: "My son",
        dateOfBirth: "2023-10-03",
        attendingPostSecondarySchool: "no",
        declaredOnTaxes: "no",
        validDependent: 0,
        isavalidDependant: true,
      },
    ],
    supportnocustodyDependants: "no",
    applicationPDPPDStatus: "no",
  },
};
