export const STUDENT_APPEAL_NOT_FOUND = "STUDENT_APPEAL_NOT_FOUND";
export const STUDENT_APPEAL_INVALID_OPERATION =
  "STUDENT_APPEAL_INVALID_OPERATION";
export const PROGRAM_START_DATE_2025_2026 = "2025-08-01";
