export const STUDENT_APPEAL_NOT_FOUND = "STUDENT_APPEAL_NOT_FOUND";
export const STUDENT_APPEAL_INVALID_OPERATION =
  "STUDENT_APPEAL_INVALID_OPERATION";
export const PROGRAM_YEAR_2025_26_START_DATE = "2025-08-01";
