export const APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND";
export const APPLICATION_STATUS_NOT_UPDATED = "APPLICATION_STATUS_NOT_UPDATED";
export const INVALID_OPERATION_IN_THE_CURRENT_STATUS =
  "INVALID_OPERATION_IN_THE_CURRENT_STATUS";
export const DISBURSEMENT_MSFAA_ALREADY_ASSOCIATED =
  "DISBURSEMENT_MSFAA_ALREADY_ASSOCIATED";
export const SUPPORTING_USER_NOT_FOUND = "SUPPORTING_USER_NOT_FOUND";
export const DISBURSEMENT_NOT_FOUND = "DISBURSEMENT_NOT_FOUND";
export const APPLICATION_EXCEPTION_ALREADY_ASSOCIATED =
  "APPLICATION_EXCEPTION_ALREADY_ASSOCIATED";
