export const ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
export const ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE =
  "ASSESSMENT_INVALID_OPERATION_IN_THE_CURRENT_STATE";
export const DISBURSEMENT_SCHEDULES_ALREADY_CREATED =
  "DISBURSEMENT_SCHEDULES_ALREADY_CREATED";
