import { MigrationInterface, QueryRunner } from "typeorm";
import { getSQLFileData } from "../utilities/sqlLoader";

export class AlterIdentityProviderColRemoveAutoGeneratedValues1674685003830
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      getSQLFileData(
        "Alter-identity-provider-col-remove-auto-generated-values.sql",
        "User",
      ),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      getSQLFileData(
        "Rollback-alter-identity-provider-col-remove-auto-generated-values.sql",
        "User",
      ),
    );
  }
}
