WITH system_user_data AS (
    SELECT
        id
    FROM
        sims.users
    WHERE
        user_name = '8fb44f70-6ce6-11ed-b307-8743a2da47ef@system'
    LIMIT
        1
)
INSERT INTO
    sims.system_lookup_configurations (
        lookup_category,
        lookup_value,
        lookup_key,
        lookup_priority,
        creator
    )
SELECT
    lookup_data.lookup_category,
    lookup_data.lookup_value,
    lookup_data.lookup_key,
    lookup_data.lookup_priority,
    su.id
FROM
    (
        VALUES
            (
                'Country',
                'Afghanistan',
                'AF',
                2
            ),
            (
                'Country',
                'Albania',
                'AL',
                2
            ),
            (
                'Country',
                'Antarctica',
                'AQ',
                2
            ),
            (
                'Country',
                'Algeria',
                'DZ',
                2
            ),
            (
                'Country',
                'American Samoa',
                'AS',
                2
            ),
            (
                'Country',
                'Andorra',
                'AD',
                2
            ),
            (
                'Country',
                'Angola',
                'AO',
                2
            ),
            (
                'Country',
                'Antigua and Barbuda',
                'AG',
                2
            ),
            (
                'Country',
                'Azerbaijan',
                'AZ',
                2
            ),
            (
                'Country',
                'Argentina',
                'AR',
                2
            ),
            (
                'Country',
                'Australia',
                'AU',
                2
            ),
            (
                'Country',
                'Austria',
                'AT',
                2
            ),
            (
                'Country',
                'Bahamas',
                'BS',
                2
            ),
            (
                'Country',
                'Bahrain',
                'BH',
                2
            ),
            (
                'Country',
                'Bangladesh',
                'BD',
                2
            ),
            (
                'Country',
                'Armenia',
                'AM',
                2
            ),
            (
                'Country',
                'Barbados',
                'BB',
                2
            ),
            (
                'Country',
                'Belgium',
                'BE',
                2
            ),
            (
                'Country',
                'Bermuda',
                'BM',
                2
            ),
            (
                'Country',
                'Bhutan',
                'BT',
                2
            ),
            (
                'Country',
                'Bolivia',
                'BO',
                2
            ),
            (
                'Country',
                'Bosnia and Herzegovina',
                'BA',
                2
            ),
            (
                'Country',
                'Botswana',
                'BW',
                2
            ),
            (
                'Country',
                'Bouvet Island',
                'BV',
                2
            ),
            (
                'Country',
                'Brazil',
                'BR',
                2
            ),
            (
                'Country',
                'Belize',
                'BZ',
                2
            ),
            (
                'Country',
                'British Indian Ocean Territory',
                'IO',
                2
            ),
            (
                'Country',
                'Solomon Islands',
                'SB',
                2
            ),
            (
                'Country',
                'Virgin Islands, British',
                'VG',
                2
            ),
            (
                'Country',
                'Brunei Darussalam',
                'BN',
                2
            ),
            (
                'Country',
                'Bulgaria',
                'BG',
                2
            ),
            (
                'Country',
                'Myanmar',
                'MM',
                2
            ),
            (
                'Country',
                'Burundi',
                'BI',
                2
            ),
            (
                'Country',
                'Belarus',
                'BY',
                2
            ),
            (
                'Country',
                'Cambodia',
                'KH',
                2
            ),
            (
                'Country',
                'Cameroon',
                'CM',
                2
            ),
            (
                'Country',
                'Canada',
                'CA',
                1
            ),
            (
                'Country',
                'Cabo Verde',
                'CV',
                2
            ),
            (
                'Country',
                'Cayman Islands',
                'KY',
                2
            ),
            (
                'Country',
                'Central African Republic',
                'CF',
                2
            ),
            (
                'Country',
                'Sri Lanka',
                'LK',
                2
            ),
            (
                'Country',
                'Chad',
                'TD',
                2
            ),
            (
                'Country',
                'Chile',
                'CL',
                2
            ),
            (
                'Country',
                'China',
                'CN',
                2
            ),
            (
                'Country',
                'Taiwan',
                'TW',
                2
            ),
            (
                'Country',
                'Christmas Island',
                'CX',
                2
            ),
            (
                'Country',
                'Cocos (Keeling) Islands',
                'CC',
                2
            ),
            (
                'Country',
                'Colombia',
                'CO',
                2
            ),
            (
                'Country',
                'Comoros',
                'KM',
                2
            ),
            (
                'Country',
                'Mayotte',
                'YT',
                2
            ),
            (
                'Country',
                'Congo, Republic of the',
                'CG',
                2
            ),
            (
                'Country',
                'Congo, Democratic Republic of the',
                'CD',
                2
            ),
            (
                'Country',
                'Cook Islands',
                'CK',
                2
            ),
            (
                'Country',
                'Costa Rica',
                'CR',
                2
            ),
            (
                'Country',
                'Croatia',
                'HR',
                2
            ),
            (
                'Country',
                'Cuba',
                'CU',
                2
            ),
            (
                'Country',
                'Cyprus',
                'CY',
                2
            ),
            (
                'Country',
                'Czechia',
                'CZ',
                2
            ),
            (
                'Country',
                'Benin',
                'BJ',
                2
            ),
            (
                'Country',
                'Denmark',
                'DK',
                2
            ),
            (
                'Country',
                'Dominica',
                'DM',
                2
            ),
            (
                'Country',
                'Dominican Republic',
                'DO',
                2
            ),
            (
                'Country',
                'Ecuador',
                'EC',
                2
            ),
            (
                'Country',
                'El Salvador',
                'SV',
                2
            ),
            (
                'Country',
                'Equatorial Guinea',
                'GQ',
                2
            ),
            (
                'Country',
                'Ethiopia',
                'ET',
                2
            ),
            (
                'Country',
                'Eritrea',
                'ER',
                2
            ),
            (
                'Country',
                'Estonia',
                'EE',
                2
            ),
            (
                'Country',
                'Faroe Islands',
                'FO',
                2
            ),
            (
                'Country',
                'Falkland Islands (Malvinas)',
                'FK',
                2
            ),
            (
                'Country',
                'South Georgia and the South Sandwich Islands',
                'GS',
                2
            ),
            (
                'Country',
                'Fiji',
                'FJ',
                2
            ),
            (
                'Country',
                'Finland',
                'FI',
                2
            ),
            (
                'Country',
                'Åland Islands',
                'AX',
                2
            ),
            (
                'Country',
                'France',
                'FR',
                2
            ),
            (
                'Country',
                'French Guiana',
                'GF',
                2
            ),
            (
                'Country',
                'French Polynesia',
                'PF',
                2
            ),
            (
                'Country',
                'French Southern Territories',
                'TF',
                2
            ),
            (
                'Country',
                'Djibouti',
                'DJ',
                2
            ),
            (
                'Country',
                'Gabon',
                'GA',
                2
            ),
            (
                'Country',
                'Georgia',
                'GE',
                2
            ),
            (
                'Country',
                'Gambia',
                'GM',
                2
            ),
            (
                'Country',
                'West Bank and Gaza',
                'PS',
                2
            ),
            (
                'Country',
                'Germany',
                'DE',
                2
            ),
            (
                'Country',
                'Ghana',
                'GH',
                2
            ),
            (
                'Country',
                'Gibraltar',
                'GI',
                2
            ),
            (
                'Country',
                'Kiribati',
                'KI',
                2
            ),
            (
                'Country',
                'Greece',
                'GR',
                2
            ),
            (
                'Country',
                'Greenland',
                'GL',
                2
            ),
            (
                'Country',
                'Grenada',
                'GD',
                2
            ),
            (
                'Country',
                'Guadeloupe',
                'GP',
                2
            ),
            (
                'Country',
                'Guam',
                'GU',
                2
            ),
            (
                'Country',
                'Guatemala',
                'GT',
                2
            ),
            (
                'Country',
                'Guinea',
                'GN',
                2
            ),
            (
                'Country',
                'Guyana',
                'GY',
                2
            ),
            (
                'Country',
                'Haiti',
                'HT',
                2
            ),
            (
                'Country',
                'Heard Island and McDonald Islands',
                'HM',
                2
            ),
            (
                'Country',
                'Holy See (Vatican City State)',
                'VA',
                2
            ),
            (
                'Country',
                'Honduras',
                'HN',
                2
            ),
            (
                'Country',
                'Hong Kong',
                'HK',
                2
            ),
            (
                'Country',
                'Hungary',
                'HU',
                2
            ),
            (
                'Country',
                'Iceland',
                'IS',
                2
            ),
            (
                'Country',
                'India',
                'IN',
                2
            ),
            (
                'Country',
                'Indonesia',
                'ID',
                2
            ),
            (
                'Country',
                'Iran',
                'IR',
                2
            ),
            (
                'Country',
                'Iraq',
                'IQ',
                2
            ),
            (
                'Country',
                'Ireland',
                'IE',
                2
            ),
            (
                'Country',
                'Israel',
                'IL',
                2
            ),
            (
                'Country',
                'Italy',
                'IT',
                2
            ),
            (
                'Country',
                'Côte d’Ivoire',
                'CI',
                2
            ),
            (
                'Country',
                'Jamaica',
                'JM',
                2
            ),
            (
                'Country',
                'Japan',
                'JP',
                2
            ),
            (
                'Country',
                'Kazakhstan',
                'KZ',
                2
            ),
            (
                'Country',
                'Jordan',
                'JO',
                2
            ),
            (
                'Country',
                'Kenya',
                'KE',
                2
            ),
            (
                'Country',
                'Korea, North',
                'KP',
                2
            ),
            (
                'Country',
                'Korea, South',
                'KR',
                2
            ),
            (
                'Country',
                'Kuwait',
                'KW',
                2
            ),
            (
                'Country',
                'Kyrgyzstan',
                'KG',
                2
            ),
            (
                'Country',
                'Laos',
                'LA',
                2
            ),
            (
                'Country',
                'Lebanon',
                'LB',
                2
            ),
            (
                'Country',
                'Lesotho',
                'LS',
                2
            ),
            (
                'Country',
                'Latvia',
                'LV',
                2
            ),
            (
                'Country',
                'Liberia',
                'LR',
                2
            ),
            (
                'Country',
                'Libya',
                'LY',
                2
            ),
            (
                'Country',
                'Liechtenstein',
                'LI',
                2
            ),
            (
                'Country',
                'Lithuania',
                'LT',
                2
            ),
            (
                'Country',
                'Luxembourg',
                'LU',
                2
            ),
            (
                'Country',
                'Macao',
                'MO',
                2
            ),
            (
                'Country',
                'Madagascar',
                'MG',
                2
            ),
            (
                'Country',
                'Malawi',
                'MW',
                2
            ),
            (
                'Country',
                'Malaysia',
                'MY',
                2
            ),
            (
                'Country',
                'Maldives',
                'MV',
                2
            ),
            (
                'Country',
                'Mali',
                'ML',
                2
            ),
            (
                'Country',
                'Malta',
                'MT',
                2
            ),
            (
                'Country',
                'Martinique',
                'MQ',
                2
            ),
            (
                'Country',
                'Mauritania',
                'MR',
                2
            ),
            (
                'Country',
                'Mauritius',
                'MU',
                2
            ),
            (
                'Country',
                'Mexico',
                'MX',
                2
            ),
            (
                'Country',
                'Monaco',
                'MC',
                2
            ),
            (
                'Country',
                'Mongolia',
                'MN',
                2
            ),
            (
                'Country',
                'Moldova',
                'MD',
                2
            ),
            (
                'Country',
                'Montenegro',
                'ME',
                2
            ),
            (
                'Country',
                'Montserrat',
                'MS',
                2
            ),
            (
                'Country',
                'Morocco',
                'MA',
                2
            ),
            (
                'Country',
                'Mozambique',
                'MZ',
                2
            ),
            (
                'Country',
                'Oman',
                'OM',
                2
            ),
            (
                'Country',
                'Namibia',
                'NA',
                2
            ),
            (
                'Country',
                'Nauru',
                'NR',
                2
            ),
            (
                'Country',
                'Nepal',
                'NP',
                2
            ),
            (
                'Country',
                'Netherlands',
                'NL',
                2
            ),
            (
                'Country',
                'Curaçao',
                'CW',
                2
            ),
            (
                'Country',
                'Aruba',
                'AW',
                2
            ),
            (
                'Country',
                'Sint Maarten (Dutch part)',
                'SX',
                2
            ),
            (
                'Country',
                'Bonaire, Sint Eustatius and Saba',
                'BQ',
                2
            ),
            (
                'Country',
                'New Caledonia',
                'NC',
                2
            ),
            (
                'Country',
                'Vanuatu',
                'VU',
                2
            ),
            (
                'Country',
                'New Zealand',
                'NZ',
                2
            ),
            (
                'Country',
                'Nicaragua',
                'NI',
                2
            ),
            (
                'Country',
                'Niger',
                'NE',
                2
            ),
            (
                'Country',
                'Nigeria',
                'NG',
                2
            ),
            (
                'Country',
                'Niue',
                'NU',
                2
            ),
            (
                'Country',
                'Norfolk Island',
                'NF',
                2
            ),
            (
                'Country',
                'Norway',
                'NO',
                2
            ),
            (
                'Country',
                'Northern Mariana Islands',
                'MP',
                2
            ),
            (
                'Country',
                'United States Minor Outlying Islands',
                'UM',
                2
            ),
            (
                'Country',
                'Micronesia, Federated States of',
                'FM',
                2
            ),
            (
                'Country',
                'Marshall Islands',
                'MH',
                2
            ),
            (
                'Country',
                'Palau',
                'PW',
                2
            ),
            (
                'Country',
                'Pakistan',
                'PK',
                2
            ),
            (
                'Country',
                'Panama',
                'PA',
                2
            ),
            (
                'Country',
                'Papua New Guinea',
                'PG',
                2
            ),
            (
                'Country',
                'Paraguay',
                'PY',
                2
            ),
            (
                'Country',
                'Peru',
                'PE',
                2
            ),
            (
                'Country',
                'Philippines',
                'PH',
                2
            ),
            (
                'Country',
                'Pitcairn',
                'PN',
                2
            ),
            (
                'Country',
                'Poland',
                'PL',
                2
            ),
            (
                'Country',
                'Portugal',
                'PT',
                2
            ),
            (
                'Country',
                'Guinea-Bissau',
                'GW',
                2
            ),
            (
                'Country',
                'Timor-Leste',
                'TL',
                2
            ),
            (
                'Country',
                'Puerto Rico',
                'PR',
                2
            ),
            (
                'Country',
                'Qatar',
                'QA',
                2
            ),
            (
                'Country',
                'Réunion',
                'RE',
                2
            ),
            (
                'Country',
                'Romania',
                'RO',
                2
            ),
            (
                'Country',
                'Russian Federation',
                'RU',
                2
            ),
            (
                'Country',
                'Rwanda',
                'RW',
                2
            ),
            (
                'Country',
                'Saint Barthélemy',
                'BL',
                2
            ),
            (
                'Country',
                'Saint Helena, Ascension and Tristan da Cunha',
                'SH',
                2
            ),
            (
                'Country',
                'Saint Kitts and Nevis',
                'KN',
                2
            ),
            (
                'Country',
                'Anguilla',
                'AI',
                2
            ),
            (
                'Country',
                'Saint Lucia',
                'LC',
                2
            ),
            (
                'Country',
                'Saint Martin (French part)',
                'MF',
                2
            ),
            (
                'Country',
                'Saint Pierre and Miquelon',
                'PM',
                2
            ),
            (
                'Country',
                'Saint Vincent and the Grenadines',
                'VC',
                2
            ),
            (
                'Country',
                'San Marino',
                'SM',
                2
            ),
            (
                'Country',
                'Sao Tome and Principe',
                'ST',
                2
            ),
            (
                'Country',
                'Sark',
                'XQ',
                2
            ),
            (
                'Country',
                'Saudi Arabia',
                'SA',
                2
            ),
            (
                'Country',
                'Senegal',
                'SN',
                2
            ),
            (
                'Country',
                'Serbia',
                'RS',
                2
            ),
            (
                'Country',
                'Seychelles',
                'SC',
                2
            ),
            (
                'Country',
                'Sierra Leone',
                'SL',
                2
            ),
            (
                'Country',
                'Singapore',
                'SG',
                2
            ),
            (
                'Country',
                'Slovakia',
                'SK',
                2
            ),
            (
                'Country',
                'Viet Nam',
                'VN',
                2
            ),
            (
                'Country',
                'Slovenia',
                'SI',
                2
            ),
            (
                'Country',
                'Somalia',
                'SO',
                2
            ),
            (
                'Country',
                'South Africa, Republic of',
                'ZA',
                2
            ),
            (
                'Country',
                'Zimbabwe',
                'ZW',
                2
            ),
            (
                'Country',
                'Spain',
                'ES',
                2
            ),
            (
                'Country',
                'South Sudan',
                'SS',
                2
            ),
            (
                'Country',
                'Sudan',
                'SD',
                2
            ),
            (
                'Country',
                'Western Sahara',
                'EH',
                2
            ),
            (
                'Country',
                'Suriname',
                'SR',
                2
            ),
            (
                'Country',
                'Svalbard and Jan Mayen',
                'SJ',
                2
            ),
            (
                'Country',
                'Eswatini',
                'SZ',
                2
            ),
            (
                'Country',
                'Sweden',
                'SE',
                2
            ),
            (
                'Country',
                'Switzerland',
                'CH',
                2
            ),
            (
                'Country',
                'Syria',
                'SY',
                2
            ),
            (
                'Country',
                'Tajikistan',
                'TJ',
                2
            ),
            (
                'Country',
                'Thailand',
                'TH',
                2
            ),
            (
                'Country',
                'Togo',
                'TG',
                2
            ),
            (
                'Country',
                'Tokelau',
                'TK',
                2
            ),
            (
                'Country',
                'Tonga',
                'TO',
                2
            ),
            (
                'Country',
                'Trinidad and Tobago',
                'TT',
                2
            ),
            (
                'Country',
                'United Arab Emirates',
                'AE',
                2
            ),
            (
                'Country',
                'Tunisia',
                'TN',
                2
            ),
            (
                'Country',
                'Türkiye',
                'TR',
                2
            ),
            (
                'Country',
                'Turkmenistan',
                'TM',
                2
            ),
            (
                'Country',
                'Turks and Caicos Islands',
                'TC',
                2
            ),
            (
                'Country',
                'Tuvalu',
                'TV',
                2
            ),
            (
                'Country',
                'Uganda',
                'UG',
                2
            ),
            (
                'Country',
                'Ukraine',
                'UA',
                2
            ),
            (
                'Country',
                'North Macedonia',
                'MK',
                2
            ),
            (
                'Country',
                'Egypt',
                'EG',
                2
            ),
            (
                'Country',
                'United Kingdom',
                'GB',
                2
            ),
            (
                'Country',
                'Guernsey',
                'GG',
                2
            ),
            (
                'Country',
                'Jersey',
                'JE',
                2
            ),
            (
                'Country',
                'Isle of Man',
                'IM',
                2
            ),
            (
                'Country',
                'Tanzania',
                'TZ',
                2
            ),
            (
                'Country',
                'United States of America',
                'US',
                2
            ),
            (
                'Country',
                'Virgin Islands, United States',
                'VI',
                2
            ),
            (
                'Country',
                'Burkina Faso',
                'BF',
                2
            ),
            (
                'Country',
                'Uruguay',
                'UY',
                2
            ),
            (
                'Country',
                'Uzbekistan',
                'UZ',
                2
            ),
            (
                'Country',
                'Venezuela',
                'VE',
                2
            ),
            (
                'Country',
                'Wallis and Futuna',
                'WF',
                2
            ),
            (
                'Country',
                'Samoa',
                'WS',
                2
            ),
            (
                'Country',
                'Yemen',
                'YE',
                2
            ),
            (
                'Country',
                'Zambia',
                'ZM',
                2
            ),
            (
                'Country',
                'Kosovo',
                'XK',
                2
            ),
            (
                'Province',
                'Alberta',
                'AB',
                2
            ),
            (
                'Province',
                'British Columbia',
                'BC',
                2
            ),
            (
                'Province',
                'Manitoba',
                'MB',
                2
            ),
            (
                'Province',
                'New Brunswick',
                'NB',
                2
            ),
            (
                'Province',
                'Newfoundland and Labrador',
                'NL',
                2
            ),
            (
                'Province',
                'Nova Scotia',
                'NS',
                2
            ),
            (
                'Province',
                'Ontario',
                'ON',
                2
            ),
            (
                'Province',
                'Prince Edward Island',
                'PE',
                2
            ),
            (
                'Province',
                'Quebec',
                'QC',
                2
            ),
            (
                'Province',
                'Saskatchewan',
                'SK',
                2
            ),
            (
                'Province',
                'Yukon',
                'YT',
                2
            ),
            (
                'Province',
                'Nunavut',
                'NU',
                2
            ),
            (
                'Province',
                'Northwest Territories',
                'NT',
                2
            )
    ) AS lookup_data(
        lookup_category,
        lookup_value,
        lookup_key,
        lookup_priority
    )
    CROSS JOIN system_user_data su;