WITH system_user_data AS (
    SELECT
        id
    FROM
        sims.users
    WHERE
        user_name = '8fb44f70-6ce6-11ed-b307-8743a2da47ef@system'
    LIMIT
        1
)
INSERT INTO
    sims.system_lookup_configurations (
        lookup_category,
        lookup_value,
        lookup_key,
        creator
    )
SELECT
    lookup_data.lookup_category,
    lookup_data.lookup_value,
    lookup_data.lookup_key,
    su.id
FROM
    (
        VALUES
            (
                'Country',
                'Afghanistan',
                'AF'
            ),
            (
                'Country',
                'Albania',
                'AL'
            ),
            (
                'Country',
                'Antarctica',
                'AQ'
            ),
            (
                'Country',
                'Algeria',
                'DZ'
            ),
            (
                'Country',
                'American Samoa',
                'AS'
            ),
            (
                'Country',
                'Andorra',
                'AD'
            ),
            (
                'Country',
                'Angola',
                'AO'
            ),
            (
                'Country',
                'Antigua and Barbuda',
                'AG'
            ),
            (
                'Country',
                'Azerbaijan',
                'AZ'
            ),
            (
                'Country',
                'Argentina',
                'AR'
            ),
            (
                'Country',
                'Australia',
                'AU'
            ),
            (
                'Country',
                'Austria',
                'AT'
            ),
            (
                'Country',
                'Bahamas',
                'BS'
            ),
            (
                'Country',
                'Bahrain',
                'BH'
            ),
            (
                'Country',
                'Bangladesh',
                'BD'
            ),
            (
                'Country',
                'Armenia',
                'AM'
            ),
            (
                'Country',
                'Barbados',
                'BB'
            ),
            (
                'Country',
                'Belgium',
                'BE'
            ),
            (
                'Country',
                'Bermuda',
                'BM'
            ),
            (
                'Country',
                'Bhutan',
                'BT'
            ),
            (
                'Country',
                'Bolivia',
                'BO'
            ),
            (
                'Country',
                'Bosnia and Herzegovina',
                'BA'
            ),
            (
                'Country',
                'Botswana',
                'BW'
            ),
            (
                'Country',
                'Bouvet Island',
                'BV'
            ),
            (
                'Country',
                'Brazil',
                'BR'
            ),
            (
                'Country',
                'Belize',
                'BZ'
            ),
            (
                'Country',
                'British Indian Ocean Territory',
                'IO'
            ),
            (
                'Country',
                'Solomon Islands',
                'SB'
            ),
            (
                'Country',
                'Virgin Islands, British',
                'VG'
            ),
            (
                'Country',
                'Brunei Darussalam',
                'BN'
            ),
            (
                'Country',
                'Bulgaria',
                'BG'
            ),
            (
                'Country',
                'Myanmar',
                'MM'
            ),
            (
                'Country',
                'Burundi',
                'BI'
            ),
            (
                'Country',
                'Belarus',
                'BY'
            ),
            (
                'Country',
                'Cambodia',
                'KH'
            ),
            (
                'Country',
                'Cameroon',
                'CM'
            ),
            (
                'Country',
                'Canada',
                'CA'
            ),
            (
                'Country',
                'Cabo Verde',
                'CV'
            ),
            (
                'Country',
                'Cayman Islands',
                'KY'
            ),
            (
                'Country',
                'Central African Republic',
                'CF'
            ),
            (
                'Country',
                'Sri Lanka',
                'LK'
            ),
            (
                'Country',
                'Chad',
                'TD'
            ),
            (
                'Country',
                'Chile',
                'CL'
            ),
            (
                'Country',
                'China',
                'CN'
            ),
            (
                'Country',
                'Taiwan',
                'TW'
            ),
            (
                'Country',
                'Christmas Island',
                'CX'
            ),
            (
                'Country',
                'Cocos (Keeling) Islands',
                'CC'
            ),
            (
                'Country',
                'Colombia',
                'CO'
            ),
            (
                'Country',
                'Comoros',
                'KM'
            ),
            (
                'Country',
                'Mayotte',
                'YT'
            ),
            (
                'Country',
                'Congo, Republic of the',
                'CG'
            ),
            (
                'Country',
                'Congo, Democratic Republic of the',
                'CD'
            ),
            (
                'Country',
                'Cook Islands',
                'CK'
            ),
            (
                'Country',
                'Costa Rica',
                'CR'
            ),
            (
                'Country',
                'Croatia',
                'HR'
            ),
            (
                'Country',
                'Cuba',
                'CU'
            ),
            (
                'Country',
                'Cyprus',
                'CY'
            ),
            (
                'Country',
                'Czechia',
                'CZ'
            ),
            (
                'Country',
                'Benin',
                'BJ'
            ),
            (
                'Country',
                'Denmark',
                'DK'
            ),
            (
                'Country',
                'Dominica',
                'DM'
            ),
            (
                'Country',
                'Dominican Republic',
                'DO'
            ),
            (
                'Country',
                'Ecuador',
                'EC'
            ),
            (
                'Country',
                'El Salvador',
                'SV'
            ),
            (
                'Country',
                'Equatorial Guinea',
                'GQ'
            ),
            (
                'Country',
                'Ethiopia',
                'ET'
            ),
            (
                'Country',
                'Eritrea',
                'ER'
            ),
            (
                'Country',
                'Estonia',
                'EE'
            ),
            (
                'Country',
                'Faroe Islands',
                'FO'
            ),
            (
                'Country',
                'Falkland Islands (Malvinas)',
                'FK'
            ),
            (
                'Country',
                'South Georgia and the South Sandwich Islands',
                'GS'
            ),
            (
                'Country',
                'Fiji',
                'FJ'
            ),
            (
                'Country',
                'Finland',
                'FI'
            ),
            (
                'Country',
                'Åland Islands',
                'AX'
            ),
            (
                'Country',
                'France',
                'FR'
            ),
            (
                'Country',
                'French Guiana',
                'GF'
            ),
            (
                'Country',
                'French Polynesia',
                'PF'
            ),
            (
                'Country',
                'French Southern Territories',
                'TF'
            ),
            (
                'Country',
                'Djibouti',
                'DJ'
            ),
            (
                'Country',
                'Gabon',
                'GA'
            ),
            (
                'Country',
                'Georgia',
                'GE'
            ),
            (
                'Country',
                'Gambia',
                'GM'
            ),
            (
                'Country',
                'West Bank and Gaza',
                'PS'
            ),
            (
                'Country',
                'Germany',
                'DE'
            ),
            (
                'Country',
                'Ghana',
                'GH'
            ),
            (
                'Country',
                'Gibraltar',
                'GI'
            ),
            (
                'Country',
                'Kiribati',
                'KI'
            ),
            (
                'Country',
                'Greece',
                'GR'
            ),
            (
                'Country',
                'Greenland',
                'GL'
            ),
            (
                'Country',
                'Grenada',
                'GD'
            ),
            (
                'Country',
                'Guadeloupe',
                'GP'
            ),
            (
                'Country',
                'Guam',
                'GU'
            ),
            (
                'Country',
                'Guatemala',
                'GT'
            ),
            (
                'Country',
                'Guinea',
                'GN'
            ),
            (
                'Country',
                'Guyana',
                'GY'
            ),
            (
                'Country',
                'Haiti',
                'HT'
            ),
            (
                'Country',
                'Heard Island and McDonald Islands',
                'HM'
            ),
            (
                'Country',
                'Holy See (Vatican City State)',
                'VA'
            ),
            (
                'Country',
                'Honduras',
                'HN'
            ),
            (
                'Country',
                'Hong Kong',
                'HK'
            ),
            (
                'Country',
                'Hungary',
                'HU'
            ),
            (
                'Country',
                'Iceland',
                'IS'
            ),
            (
                'Country',
                'India',
                'IN'
            ),
            (
                'Country',
                'Indonesia',
                'ID'
            ),
            (
                'Country',
                'Iran',
                'IR'
            ),
            (
                'Country',
                'Iraq',
                'IQ'
            ),
            (
                'Country',
                'Ireland',
                'IE'
            ),
            (
                'Country',
                'Israel',
                'IL'
            ),
            (
                'Country',
                'Italy',
                'IT'
            ),
            (
                'Country',
                'Côte d’Ivoire',
                'CI'
            ),
            (
                'Country',
                'Jamaica',
                'JM'
            ),
            (
                'Country',
                'Japan',
                'JP'
            ),
            (
                'Country',
                'Kazakhstan',
                'KZ'
            ),
            (
                'Country',
                'Jordan',
                'JO'
            ),
            (
                'Country',
                'Kenya',
                'KE'
            ),
            (
                'Country',
                'Korea, North',
                'KP'
            ),
            (
                'Country',
                'Korea, South',
                'KR'
            ),
            (
                'Country',
                'Kuwait',
                'KW'
            ),
            (
                'Country',
                'Kyrgyzstan',
                'KG'
            ),
            (
                'Country',
                'Laos',
                'LA'
            ),
            (
                'Country',
                'Lebanon',
                'LB'
            ),
            (
                'Country',
                'Lesotho',
                'LS'
            ),
            (
                'Country',
                'Latvia',
                'LV'
            ),
            (
                'Country',
                'Liberia',
                'LR'
            ),
            (
                'Country',
                'Libya',
                'LY'
            ),
            (
                'Country',
                'Liechtenstein',
                'LI'
            ),
            (
                'Country',
                'Lithuania',
                'LT'
            ),
            (
                'Country',
                'Luxembourg',
                'LU'
            ),
            (
                'Country',
                'Macao',
                'MO'
            ),
            (
                'Country',
                'Madagascar',
                'MG'
            ),
            (
                'Country',
                'Malawi',
                'MW'
            ),
            (
                'Country',
                'Malaysia',
                'MY'
            ),
            (
                'Country',
                'Maldives',
                'MV'
            ),
            (
                'Country',
                'Mali',
                'ML'
            ),
            (
                'Country',
                'Malta',
                'MT'
            ),
            (
                'Country',
                'Martinique',
                'MQ'
            ),
            (
                'Country',
                'Mauritania',
                'MR'
            ),
            (
                'Country',
                'Mauritius',
                'MU'
            ),
            (
                'Country',
                'Mexico',
                'MX'
            ),
            (
                'Country',
                'Monaco',
                'MC'
            ),
            (
                'Country',
                'Mongolia',
                'MN'
            ),
            (
                'Country',
                'Moldova',
                'MD'
            ),
            (
                'Country',
                'Montenegro',
                'ME'
            ),
            (
                'Country',
                'Montserrat',
                'MS'
            ),
            (
                'Country',
                'Morocco',
                'MA'
            ),
            (
                'Country',
                'Mozambique',
                'MZ'
            ),
            (
                'Country',
                'Oman',
                'OM'
            ),
            (
                'Country',
                'Namibia',
                'NA'
            ),
            (
                'Country',
                'Nauru',
                'NR'
            ),
            (
                'Country',
                'Nepal',
                'NP'
            ),
            (
                'Country',
                'Netherlands',
                'NL'
            ),
            (
                'Country',
                'Curaçao',
                'CW'
            ),
            (
                'Country',
                'Aruba',
                'AW'
            ),
            (
                'Country',
                'Sint Maarten (Dutch part)',
                'SX'
            ),
            (
                'Country',
                'Bonaire, Sint Eustatius and Saba',
                'BQ'
            ),
            (
                'Country',
                'New Caledonia',
                'NC'
            ),
            (
                'Country',
                'Vanuatu',
                'VU'
            ),
            (
                'Country',
                'New Zealand',
                'NZ'
            ),
            (
                'Country',
                'Nicaragua',
                'NI'
            ),
            (
                'Country',
                'Niger',
                'NE'
            ),
            (
                'Country',
                'Nigeria',
                'NG'
            ),
            (
                'Country',
                'Niue',
                'NU'
            ),
            (
                'Country',
                'Norfolk Island',
                'NF'
            ),
            (
                'Country',
                'Norway',
                'NO'
            ),
            (
                'Country',
                'Northern Mariana Islands',
                'MP'
            ),
            (
                'Country',
                'United States Minor Outlying Islands',
                'UM'
            ),
            (
                'Country',
                'Micronesia, Federated States of',
                'FM'
            ),
            (
                'Country',
                'Marshall Islands',
                'MH'
            ),
            (
                'Country',
                'Palau',
                'PW'
            ),
            (
                'Country',
                'Pakistan',
                'PK'
            ),
            (
                'Country',
                'Panama',
                'PA'
            ),
            (
                'Country',
                'Papua New Guinea',
                'PG'
            ),
            (
                'Country',
                'Paraguay',
                'PY'
            ),
            (
                'Country',
                'Peru',
                'PE'
            ),
            (
                'Country',
                'Philippines',
                'PH'
            ),
            (
                'Country',
                'Pitcairn',
                'PN'
            ),
            (
                'Country',
                'Poland',
                'PL'
            ),
            (
                'Country',
                'Portugal',
                'PT'
            ),
            (
                'Country',
                'Guinea-Bissau',
                'GW'
            ),
            (
                'Country',
                'Timor-Leste',
                'TL'
            ),
            (
                'Country',
                'Puerto Rico',
                'PR'
            ),
            (
                'Country',
                'Qatar',
                'QA'
            ),
            (
                'Country',
                'Réunion',
                'RE'
            ),
            (
                'Country',
                'Romania',
                'RO'
            ),
            (
                'Country',
                'Russian Federation',
                'RU'
            ),
            (
                'Country',
                'Rwanda',
                'RW'
            ),
            (
                'Country',
                'Saint Barthélemy',
                'BL'
            ),
            (
                'Country',
                'Saint Helena, Ascension and Tristan da Cunha',
                'SH'
            ),
            (
                'Country',
                'Saint Kitts and Nevis',
                'KN'
            ),
            (
                'Country',
                'Anguilla',
                'AI'
            ),
            (
                'Country',
                'Saint Lucia',
                'LC'
            ),
            (
                'Country',
                'Saint Martin (French part)',
                'MF'
            ),
            (
                'Country',
                'Saint Pierre and Miquelon',
                'PM'
            ),
            (
                'Country',
                'Saint Vincent and the Grenadines',
                'VC'
            ),
            (
                'Country',
                'San Marino',
                'SM'
            ),
            (
                'Country',
                'Sao Tome and Principe',
                'ST'
            ),
            (
                'Country',
                'Sark',
                'XQ'
            ),
            (
                'Country',
                'Saudi Arabia',
                'SA'
            ),
            (
                'Country',
                'Senegal',
                'SN'
            ),
            (
                'Country',
                'Serbia',
                'RS'
            ),
            (
                'Country',
                'Seychelles',
                'SC'
            ),
            (
                'Country',
                'Sierra Leone',
                'SL'
            ),
            (
                'Country',
                'Singapore',
                'SG'
            ),
            (
                'Country',
                'Slovakia',
                'SK'
            ),
            (
                'Country',
                'Viet Nam',
                'VN'
            ),
            (
                'Country',
                'Slovenia',
                'SI'
            ),
            (
                'Country',
                'Somalia',
                'SO'
            ),
            (
                'Country',
                'South Africa, Republic of',
                'ZA'
            ),
            (
                'Country',
                'Zimbabwe',
                'ZW'
            ),
            (
                'Country',
                'Spain',
                'ES'
            ),
            (
                'Country',
                'South Sudan',
                'SS'
            ),
            (
                'Country',
                'Sudan',
                'SD'
            ),
            (
                'Country',
                'Western Sahara',
                'EH'
            ),
            (
                'Country',
                'Suriname',
                'SR'
            ),
            (
                'Country',
                'Svalbard and Jan Mayen',
                'SJ'
            ),
            (
                'Country',
                'Eswatini',
                'SZ'
            ),
            (
                'Country',
                'Sweden',
                'SE'
            ),
            (
                'Country',
                'Switzerland',
                'CH'
            ),
            (
                'Country',
                'Syria',
                'SY'
            ),
            (
                'Country',
                'Tajikistan',
                'TJ'
            ),
            (
                'Country',
                'Thailand',
                'TH'
            ),
            (
                'Country',
                'Togo',
                'TG'
            ),
            (
                'Country',
                'Tokelau',
                'TK'
            ),
            (
                'Country',
                'Tonga',
                'TO'
            ),
            (
                'Country',
                'Trinidad and Tobago',
                'TT'
            ),
            (
                'Country',
                'United Arab Emirates',
                'AE'
            ),
            (
                'Country',
                'Tunisia',
                'TN'
            ),
            (
                'Country',
                'Türkiye',
                'TR'
            ),
            (
                'Country',
                'Turkmenistan',
                'TM'
            ),
            (
                'Country',
                'Turks and Caicos Islands',
                'TC'
            ),
            (
                'Country',
                'Tuvalu',
                'TV'
            ),
            (
                'Country',
                'Uganda',
                'UG'
            ),
            (
                'Country',
                'Ukraine',
                'UA'
            ),
            (
                'Country',
                'North Macedonia',
                'MK'
            ),
            (
                'Country',
                'Egypt',
                'EG'
            ),
            (
                'Country',
                'United Kingdom',
                'GB'
            ),
            (
                'Country',
                'Guernsey',
                'GG'
            ),
            (
                'Country',
                'Jersey',
                'JE'
            ),
            (
                'Country',
                'Isle of Man',
                'IM'
            ),
            (
                'Country',
                'Tanzania',
                'TZ'
            ),
            (
                'Country',
                'United States of America',
                'US'
            ),
            (
                'Country',
                'Virgin Islands, United States',
                'VI'
            ),
            (
                'Country',
                'Burkina Faso',
                'BF'
            ),
            (
                'Country',
                'Uruguay',
                'UY'
            ),
            (
                'Country',
                'Uzbekistan',
                'UZ'
            ),
            (
                'Country',
                'Venezuela',
                'VE'
            ),
            (
                'Country',
                'Wallis and Futuna',
                'WF'
            ),
            (
                'Country',
                'Samoa',
                'WS'
            ),
            (
                'Country',
                'Yemen',
                'YE'
            ),
            (
                'Country',
                'Zambia',
                'ZM'
            ),
            (
                'Country',
                'Kosovo',
                'XK'
            ),
            (
                'Province',
                'Alberta',
                'AB'
            ),
            (
                'Province',
                'British Columbia',
                'BC'
            ),
            (
                'Province',
                'Manitoba',
                'MB'
            ),
            (
                'Province',
                'New Brunswick',
                'NB'
            ),
            (
                'Province',
                'Newfoundland and Labrador',
                'NL'
            ),
            (
                'Province',
                'Nova Scotia',
                'NS'
            ),
            (
                'Province',
                'Ontario',
                'ON'
            ),
            (
                'Province',
                'Prince Edward Island',
                'PE'
            ),
            (
                'Province',
                'Quebec',
                'QC'
            ),
            (
                'Province',
                'Saskatchewan',
                'SK'
            ),
            (
                'Province',
                'Yukon',
                'YT'
            ),
            (
                'Province',
                'Nunavut',
                'NU'
            ),
            (
                'Province',
                'Northwest Territories',
                'NT'
            )
    ) AS lookup_data(lookup_category, lookup_value, lookup_key)
    CROSS JOIN system_user_data su;