apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: >-
      Creates a new database on a postgres server
  name: ${DB_NAME}-createdb
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${JOB_NAME}-create-db
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 1800
      backoffLimit: 6
      template:
        metadata:
          name: create-db
        spec:
          restartPolicy: Never
          containers:
            - name: create-db
              image: ${IMAGE_REGISTRY}/${BUILD_NAMESPACE}/${POSTGRES_IMAGE_TAG}
              command: ["createdb"]
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_USERNAME_KEY}
                      name: ${DB_SECRET_NAME}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ${DB_PASSWORD_KEY}
                      name: ${DB_SECRET_NAME}
                - name: PGHOST
                  value: ${DB_SERVICE}
                - name: PGDATABASE
                  value: ${DB_NAME}
parameters:
  - name: DB_NAME
    required: true
  - name: DB_SERVICE
    value: patroni-master
  - name: DB_SECRET_NAME
    value: patroni-creds
  - name: DB_USERNAME_KEY
    value: superuser-username
  - name: DB_PASSWORD_KEY
    value: superuser-password
  - name: POSTGRES_IMAGE_TAG
    value: patroni:12-latest
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: BUILD_NAMESPACE
    required: true
  - name: DATABASE_NAME_KEY
    value: database-name
  - name: JOB_NAME
    required: true
