export const ColumnNames = {
  ID: "id",
  CreateTimestamp: "created_at",
  UpdateTimestamp: "updated_at",
  Creator: "creator",
  Modifier: "modifier",
  StudentId: "student_id",
  NoteId: "note_id",
  InstitutionId: "institution_id",
};

export const TableNames = {
  User: "users",
  Student: "students",
  StudentUser: "student_users",
  StudentAccountApplications: "student_account_applications",
  Institution: "institutions",
  Applications: "applications",
  Announcements: "announcements",
  StudentsFiles: "student_files",
  ApplicationStudentFiles: "application_student_files",
  EducationPrograms: "education_programs",
  EducationProgramsOfferings: "education_programs_offerings",
  ProgramYear: "program_years",
  PIRDeniedReason: "pir_denied_reason",
  MSFAANumbers: "msfaa_numbers",
  COEDeniedReason: "coe_denied_reasons",
  CRAIncomeVerification: "cra_income_verifications",
  SINValidations: "sin_validations",
  SupportingUsers: "supporting_users",
  Restrictions: "restrictions",
  StudentRestrictions: "student_restrictions",
  SFASIndividuals: "sfas_individuals",
  SFASApplications: "sfas_applications",
  SFASRestrictions: "sfas_restrictions",
  DisbursementSchedule: "disbursement_schedules",
  DisbursementValue: "disbursement_values",
  FederalRestrictions: "federal_restrictions",
  DisbursementFeedbackErrors: "disbursement_feedback_errors",
  DisbursementOverawards: "disbursement_overawards",
  Notes: "notes",
  StudentNotes: "student_notes",
  InstitutionNotes: "institution_notes",
  InstitutionRestrictions: "institution_restrictions",
  SFASPartTimeApplications: "sfas_part_time_applications",
  DesignationAgreements: "designation_agreements",
  DesignationAgreementLocations: "designation_agreement_locations",
  StudentAppeals: "student_appeals",
  StudentAppealRequests: "student_appeal_requests",
  StudentScholasticStandings: "student_scholastic_standings",
  StudentAssessments: "student_assessments",
  ReportsConfig: "report_configs",
  ApplicationExceptions: "application_exceptions",
  ApplicationExceptionRequests: "application_exception_requests",
  DisbursementReceipts: "disbursement_receipts",
  DisbursementReceiptValues: "disbursement_receipt_values",
  Messages: "notification_messages",
  Notifications: "notifications",
  QueueConfigurations: "queue_configurations",
  ApplicationOfferingChangeRequests: "application_offering_change_requests",
  StudentLoanBalances: "student_loan_balances",
  ECertFeedbackErrors: "ecert_feedback_errors",
  CASSuppliers: "cas_suppliers",
  ApplicationRestrictionBypasses: "application_restriction_bypasses",
  BetaUsersAuthorizations: "beta_users_authorizations",
  SFASBridgeLogs: "sfas_bridge_logs",
};

export const INSTITUTION_TYPE_BC_PUBLIC = 1;
export const INSTITUTION_TYPE_BC_PRIVATE = 2;
