import { Injectable } from "@nestjs/common";
import { DataSource } from "typeorm";
import { ORM_CACHE_LIFETIME } from "@sims/utilities";
import { LoggerService } from "@sims/utilities/logger";

/**
 * Centralizes the creation and invalidation of the TypeORM query result
 * cache identifiers so cached queries can be found and removed by their
 * business purpose instead of relying on ad-hoc strings spread across
 * the code.
 */
@Injectable()
export class ORMCacheManager {
  constructor(
    private readonly dataSource: DataSource,
    private readonly logger: LoggerService,
  ) {}

  /**
   * Cache identifier for the query that loads a user's login information
   * (id, isActive, student id, identity provider) during authentication.
   * @param userName user name (same as Keycloak) used for the login.
   * @returns cache identifier.
   */
  getUserLoginCacheId(userName: string): string {
    return `user-login_${userName}`;
  }

  /**
   * Removes the cached login information for a user. Must be called right
   * after any change that impacts the login query result, for instance,
   * when a user is activated or deactivated, so the change takes effect
   * immediately instead of waiting for the cache to expire.
   * @param userName user name (same as Keycloak) used for the login.
   */
  async clearUserLoginCache(userName: string): Promise<void> {
    await this.clearCache(this.getUserLoginCacheId(userName));
  }

  /**
   * Cache identifier for the query that loads an institution user's
   * authorizations (locations and roles) during authentication.
   * @param userName user name (same as Keycloak) used for the login.
   * @returns cache identifier.
   */
  getUserAuthorizationsCacheId(userName: string): string {
    return `user-authorizations_${userName}`;
  }

  /**
   * Removes the cached authorizations for an institution user. Must be
   * called whenever the user's roles/locations assignments change.
   * @param userName user name (same as Keycloak) used for the login.
   */
  async clearUserAuthorizationsCache(userName: string): Promise<void> {
    await this.clearCache(this.getUserAuthorizationsCacheId(userName));
  }

  /**
   * Cache identifier for the query that loads an institution's type.
   * @param institutionId institution id.
   * @returns cache identifier.
   */
  getInstitutionTypeCacheId(institutionId: number): string {
    return `institution-type_${institutionId}`;
  }

  /**
   * Removes the cached institution type. Must be called whenever the
   * institution's type is updated.
   * @param institutionId institution id.
   */
  async clearInstitutionTypeCache(institutionId: number): Promise<void> {
    await this.clearCache(this.getInstitutionTypeCacheId(institutionId));
  }

  /**
   * Cache identifier for the query that loads all location ids of an
   * institution, used to authorize institution admin users during login.
   * @param institutionId institution id.
   * @returns cache identifier.
   */
  getInstitutionLocationsCacheId(institutionId: number): string {
    return `institution-locations_${institutionId}`;
  }

  /**
   * Removes the cached institution locations ids. Must be called whenever
   * a location is added to the institution.
   * @param institutionId institution id.
   */
  async clearInstitutionLocationsCache(institutionId: number): Promise<void> {
    await this.clearCache(this.getInstitutionLocationsCacheId(institutionId));
  }

  /**
   * Builds the cache options, using the default ORM cache lifetime, to be
   * used either as the `cache` option of a `find`/`findOne` call or as the
   * arguments of a query builder's `cache` method.
   * @param cacheId cache identifier, usually generated by one of the
   * `get*CacheId` methods above.
   * @returns cache options with the identifier and the default lifetime.
   */
  getOptionsCache(cacheId: string): { id: string; milliseconds: number } {
    return { id: cacheId, milliseconds: ORM_CACHE_LIFETIME };
  }

  /**
   * Removes one or more cached query results by their cache identifiers.
   * Silently ignored if the query result cache is disabled (e.g. Redis
   * is down or the cache was turned off through configuration).
   * Errors while communicating with the cache store (e.g. Redis is
   * unreachable) are logged but not propagated, so a temporary cache
   * outage never prevents the underlying database write from succeeding.
   * @param cacheId one or more cache identifiers to be removed.
   */
  private async clearCache(cacheId: string | string[]): Promise<void> {
    const queryResultCache = this.dataSource.queryResultCache;
    if (!queryResultCache) {
      return;
    }
    const cacheIds = Array.isArray(cacheId) ? cacheId : [cacheId];
    try {
      await queryResultCache.remove(cacheIds);
    } catch (error: unknown) {
      this.logger.error(
        `Error while removing cache identifiers ${cacheIds.join(", ")}.`,
        error,
      );
    }
  }

  /**
   * Clears the entire query result cache.
   */
  async clear(): Promise<void> {
    const queryResultCache = this.dataSource.queryResultCache;
    if (!queryResultCache) {
      return;
    }
    try {
      await queryResultCache.clear();
    } catch (error: unknown) {
      this.logger.error(`Error while clearing the cache.`, error);
    }
  }
}
