ALTER TABLE
    sims.sfas_applications DROP COLUMN application_number,
    DROP COLUMN living_arrangements,
    DROP COLUMN marital_status,
    DROP COLUMN marriage_date,
    DROP COLUMN bc_residency_flag,
    DROP COLUMN permanent_residency_flag,
    DROP COLUMN gross_income_previous_year,
    DROP COLUMN institution_code,
    DROP COLUMN application_status_code,
    DROP COLUMN education_period_weeks,
    DROP COLUMN course_load,
    DROP COLUMN assessed_costs_living_allowance,
    DROP COLUMN assessed_costs_extra_shelter,
    DROP COLUMN assessed_costs_child_care,
    DROP COLUMN assessed_costs_alimony,
    DROP COLUMN assessed_costs_local_transport,
    DROP COLUMN assessed_costs_return_transport,
    DROP COLUMN assessed_costs_tuition,
    DROP COLUMN assessed_costs_books_and_supplies,
    DROP COLUMN assessed_costs_exceptional_expenses,
    DROP COLUMN assessed_costs_other,
    DROP COLUMN assessed_costs_discretionary_expenses,
    DROP COLUMN withdrawal_date,
    DROP COLUMN withdrawal_reason,
    DROP COLUMN withdrawal_active_flag;