apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
data:
  clamd.conf: |-
{{ .Files.Get (printf "configurations/%s/clamd.conf" .Values.configVersion) | indent 4 }}
  freshclam.conf: |-
{{ .Files.Get (printf "configurations/%s/freshclam.conf" .Values.configVersion) | indent 4 }}
