// * MINIMUM_TOKEN_VALIDITY in seconds, i,e 180 seconds is 3 minutes
export const MINIMUM_TOKEN_VALIDITY = 180;
// * MINIMUM_IDLE_TIME_FOR_WARNING_STUDENT in minutes
export const MINIMUM_IDLE_TIME_FOR_WARNING_STUDENT = 4.5;
// * MINIMUM_IDLE_TIME_FOR_WARNING_STUDENT in minutes
export const MINIMUM_IDLE_TIME_FOR_WARNING_INSTITUTION = 4.5;
// * MINIMUM_IDLE_TIME_FOR_WARNING_STUDENT in minutes
export const MINIMUM_IDLE_TIME_FOR_WARNING_SUPPORTING_USER = 4.5;
// * MINIMUM_IDLE_TIME_FOR_WARNING_STUDENT in minutes
export const MINIMUM_IDLE_TIME_FOR_WARNING_AEST = 4.5;
// * COUNT_DOWN_TIMER_FOR_LOGOUT in seconds
export const COUNT_DOWN_TIMER_FOR_LOGOUT = 30;
