import { Module } from "@nestjs/common";
import {
  ApplicationService,
  FormService,
  StudentService,
  ProgramYearService,
  EducationProgramOfferingService,
  DisbursementScheduleService,
  InstitutionLocationService,
  EducationProgramService,
  StudentFileService,
  StudentRestrictionService,
  DesignationAgreementLocationService,
  StudentAssessmentService,
  StudentAppealService,
  StudentAppealRequestsService,
  RestrictionService,
  EducationProgramOfferingValidationService,
  ApplicationExceptionService,
  StudentScholasticStandingsService,
  CRAIncomeVerificationService,
  SupportingUserService,
  StudentAccountApplicationsService,
  ApplicationOfferingChangeRequestService,
  InstitutionService,
  BCeIDService,
  InstitutionUserAuthService,
  UserService,
  AnnouncementService,
  ApplicationRestrictionBypassService,
  InstitutionRestrictionService,
  FormSubmissionService,
} from "./services";
import {
  ApplicationStudentsController,
  StudentStudentsController,
  StudentAppealStudentsController,
  InstitutionLocationStudentsController,
  AssessmentStudentsController,
  AssessmentControllerService,
  StudentControllerService,
  EducationProgramStudentsController,
  StudentAccountApplicationStudentsController,
  EducationProgramOfferingStudentsController,
  ApplicationOfferingChangeRequestStudentsController,
  ApplicationOfferingChangeRequestControllerService,
  EducationProgramOfferingControllerService,
  RestrictionStudentsController,
  ProgramYearStudentsController,
  ApplicationControllerService,
  OverawardStudentsController,
  OverawardControllerService,
  StudentAppealControllerService,
  ScholasticStandingControllerService,
  ScholasticStandingStudentsController,
  ProgramYearControllerService,
  AnnouncementStudentsController,
  SupportingUserControllerService,
  SupportingUserStudentsController,
  FormSubmissionStudentsController,
} from "./route-controllers";
import { AuthModule } from "./auth/auth.module";
import { ConfigModule } from "@sims/utilities/config";
import {
  DisbursementOverawardService,
  SequenceControlService,
  StudentRestrictionSharedService,
  WorkflowClientService,
  NoteSharedService,
  RestrictionSharedService,
  ConfirmationOfEnrollmentService,
  AssessmentSequentialProcessingService,
  DisbursementScheduleSharedService,
  StudentFileSharedService,
} from "@sims/services";
import {
  SFASIndividualService,
  SFASApplicationService,
  SFASPartTimeApplicationsService,
} from "@sims/services/sfas";
import { ATBCIntegrationModule } from "@sims/integrations/atbc-integration";
import { ECertIntegrationModule } from "@sims/integrations/esdc-integration";
import { ObjectStorageModule } from "@sims/integrations/object-storage";
import {
  ConfigurationContextValidator,
  PendingConcurrencyValidator,
  ApplicationEligibleAppealsValidator,
  FormSubmissionValidator,
} from "./services/form-submission/form-submission-validator";
import {
  SupplementaryDataProgramYear,
  SupplementaryDataParents,
  SupplementaryDataLoader,
} from "./services/form-submission/form-supplementary-data";

@Module({
  imports: [
    AuthModule,
    ConfigModule,
    ATBCIntegrationModule,
    ECertIntegrationModule,
    ObjectStorageModule,
    //FormSubmissionModule,
  ],
  controllers: [
    ApplicationStudentsController,
    StudentStudentsController,
    StudentAppealStudentsController,
    InstitutionLocationStudentsController,
    AssessmentStudentsController,
    EducationProgramStudentsController,
    StudentAccountApplicationStudentsController,
    EducationProgramOfferingStudentsController,
    RestrictionStudentsController,
    ProgramYearStudentsController,
    OverawardStudentsController,
    ApplicationOfferingChangeRequestStudentsController,
    ScholasticStandingStudentsController,
    AnnouncementStudentsController,
    SupportingUserStudentsController,
    FormSubmissionStudentsController,
  ],
  providers: [
    AnnouncementService,
    WorkflowClientService,
    ApplicationService,
    FormService,
    StudentService,
    ProgramYearControllerService,
    ProgramYearService,
    EducationProgramOfferingService,
    DisbursementScheduleService,
    InstitutionLocationService,
    EducationProgramService,
    SequenceControlService,
    StudentFileService,
    StudentFileSharedService,
    SFASIndividualService,
    SFASApplicationService,
    SFASPartTimeApplicationsService,
    StudentRestrictionService,
    DesignationAgreementLocationService,
    StudentAssessmentService,
    ApplicationControllerService,
    StudentAppealService,
    StudentAppealRequestsService,
    AssessmentControllerService,
    StudentControllerService,
    RestrictionService,
    StudentAccountApplicationsService,
    EducationProgramOfferingControllerService,
    EducationProgramOfferingValidationService,
    ApplicationExceptionService,
    StudentScholasticStandingsService,
    CRAIncomeVerificationService,
    SupportingUserService,
    StudentRestrictionSharedService,
    ApplicationRestrictionBypassService,
    RestrictionSharedService,
    DisbursementOverawardService,
    NoteSharedService,
    OverawardControllerService,
    StudentAppealControllerService,
    ConfirmationOfEnrollmentService,
    ApplicationOfferingChangeRequestControllerService,
    ApplicationOfferingChangeRequestService,
    ScholasticStandingControllerService,
    AssessmentSequentialProcessingService,
    InstitutionService,
    BCeIDService,
    InstitutionUserAuthService,
    UserService,
    SupportingUserControllerService,
    DisbursementScheduleSharedService,
    InstitutionRestrictionService,
    // Form Validators
    ConfigurationContextValidator,
    PendingConcurrencyValidator,
    ApplicationEligibleAppealsValidator,
    FormSubmissionValidator,
    // Form Supplementary Data Loaders
    SupplementaryDataProgramYear,
    SupplementaryDataParents,
    FormSubmissionService,
    SupplementaryDataLoader,
    // Form Submission Service (used by validators and controllers, but not exported outside of this module).
    FormSubmissionService,
  ],
})
export class AppStudentsModule {}
