/**
 * Full-time student financial aid application data payload used for formio dry-run
 * validation during load testing. This payload represents a complete 2026-27
 * full-time application and is designed to pass formio schema validation.
 */
export const APPLICATION_SUBMISSION_DATA = {
  workflowName: "assessment-gateway-v2",
  applicationExceptionsStrategy: "verify-unique-application-exceptions",
  maxIncome: "100000000",
  isChangeRequestApplication: false,
  isProgramSectionReadOnly: false,
  allowBetaInstitutionsOnly: false,
  applicationSubmissionDeadlineWeeks: 6,
  selectedLocation: 14,
  mySchoolIsNotListed: false,
  studentNumber: "",
  selectedProgramDesc: {
    id: 211,
    name: "Computer Sciences",
    description: "Computer science description",
    credentialType: "graduateDiploma",
    credentialTypeToDisplay: "Graduate Diploma",
    deliveryMethod: "Onsite",
  },
  studyPeriodMaxDays: "365",
  studentGivenNames: "MATT",
  studentDateOfBirth: "Nov 25 1985",
  studentHomeAddress: "123 Humboldt St, Victoria, BC, V9V1V1, canada",
  studentEmail: "simsfive@test.ca",
  studentLastName: "FRANKY",
  studentGender: "man",
  studentPhoneNumber: "7789221234",
  disabilityStatus: "Not requested",
  studentInfoConfirmed: true,
  citizenship: "canadianCitizen",
  indigenousStatus: "no",
  youthInCare: "no",
  everDeclaredBankruptcy: "no",
  addTrustContactToContactSABC: "no",
  roiInformation: [
    {
      firstName: "",
      lastName: "",
      relationshipWithThisContact: "",
    },
  ],
  relationshipStatus: "single",
  hasDependents: "no",
  applicationPDPPDStatus: "no",
  craConsent: true,
  dependantstatus: "dependant",
  studentAidBcConsent: true,
  applicationId: "",
  applicationStatus: "",
  selectedLocationName: "Victoria College",
  howWillYouBeAttendingTheProgram: "Full Time",
  myProgramNotListed: {
    programnotListed: false,
  },
  programYearStartDate: "2026-08-01",
  programYearEndDate: "2027-07-31",
  programYear: "2026",
  calculatedTaxYear: 2025,
  currentTaxYear: "2026",
  taxReturnIncome: 15000,
  outOfHighSchoolFor4Years: "no",
  whenDidYouGraduateOrLeaveHighSchool: "2023-10-03",
  fulltimelabourForce: "no",
  fulltimeMonthsOfStudy: 0,
  duringStudyCoopPaidWork: "no",
  childSupport: "no",
  parentvoluntaryContributions: "no",
  governmentFunding: "no",
  nonGovernmentFunding: "no",
  scholarshipsReceived: "no",
  bcIncomeassistanceforDisabilities: "no",
  livingAtHome: "no",
  considerCostToRelocateToDifferentCity: "no",
  additionalTransportRequested: "no",
  parentInformationStatus: "required",
  parentsDeceased: "no",
  estrangedFromParents: "no",
  parents: [
    {
      parentFullName: "Test Parent",
      parentIsAbleToReport: "no",
    },
  ],
  parentbcResident: "yes",
  isReadOnly: false,
  isFulltimeAllowed: true,
  applicationOfferingIntensityValue: "Full Time",
  pirResubmissionDate: "",
  hasPreviouslyCompletedPIR: false,
  myStudyPeriodIsntListed: {
    offeringnotListed: false,
  },
};
