/**
 * Full-time student financial aid application data payload used as the initial
 * draft application data during load test setup. This payload represents a
 * complete 2026-27 full-time application aligned with the form schema.
 */
export const APPLICATION_SUBMISSION_DATA = {
  workflowName: "assessment-gateway-v2",
  applicationExceptionsStrategy: "verify-unique-application-exceptions",
  maxIncome: "100000000",
  isChangeRequestApplication: false,
  isProgramSectionReadOnly: false,
  allowBetaInstitutionsOnly: false,
  selectedLocation: 14,
  mySchoolIsNotListed: false,
  studentNumber: "",
  programYear: "2026",
  calculatedTaxYear: 2025,
  selectedProgramDesc: {
    id: 211,
    name: "Computer Sciences",
    description: "Computer science description",
    credentialType: "graduateDiploma",
    credentialTypeToDisplay: "Graduate Diploma",
    deliveryMethod: "Onsite",
  },
  studyPeriodMaxDays: "365",
  currentTaxYear: "2026",
  programPersistentProperties: [
    "selectedLocation",
    "mySchoolIsNotListed",
    "selectedProgram",
    "myProgramNotListed",
    "programName",
    "programDescription",
    "studystartDate",
    "studyendDate",
    "selectedOffering",
    "myStudyPeriodIsntListed",
    "studentNumber",
    "pirResubmissionDate",
  ],
  selectedLocationProgramRestrictions: [],
  isSelectedLocationProgramRestricted: false,
  pirResubmissionDate: "",
  studentGivenNames: "MATT",
  studentDateOfBirth: "Nov 25 1985",
  studentHomeAddress: "123 Humboldt St, Victoria, BC, V9V1V1, canada",
  studentEmail: "simsfive@test.ca",
  studentLastName: "FRANKY",
  studentGender: "man",
  studentPhoneNumber: "7789221234",
  disabilityStatus: "Not requested",
  studentProfileDisabilityStatusValue: "Not requested",
  studentProfileModifiedIndependentStatusValue: "Not requested",
  maxUploadedFiles: 25,
  studentInfoConfirmed: true,
  citizenship: "canadianCitizen",
  relationshipStatus: "single",
  indigenousStatus: "no",
  youthInCare: "no",
  everDeclaredBankruptcy: "no",
  outOfHighSchoolFor4Years: "yes",
  whenDidYouGraduateOrLeaveHighSchool: "2023-10-03",
  fulltimelabourForce: "no",
  duringStudyCoopPaidWork: "no",
  hasDependents: "no",
  dependants: [],
  applicationPDPPDStatus: "no",
  addTrustContactToContactSABC: "no",
  parentInformationStatus: "notRequired",
  dependantstatus: "independant",
  bcResident: "yes",
  taxReturnIncome: 10000,
  parentvoluntaryContributions: "no",
  restrictions: [],
  roiInformation: [
    {
      firstName: "",
      lastName: "",
      relationshipWithThisContact: "",
    },
  ],
  craConsent: true,
  childSupport: "no",
  scholarshipsReceived: "no",
  bcIncomeassistanceforDisabilities: "no",
  governmentFunding: "no",
  nonGovernmentFunding: "no",
  livingAtHome: "no",
  considerCostToRelocateToDifferentCity: "no",
  additionalTransportRequested: "no",
  studentAidBcConsent: true,
  applicationId: "",
  applicationStatus: "",
  selectedLocationName: "Victoria College",
  selectedProgramName: "Computer Sciences",
  myProgramNotListed: { programnotListed: false },
  myStudyPeriodIsntListed: { offeringnotListed: false },
  programYearStartDate: "2026-08-01",
  programYearEndDate: "2027-07-31",
  fulltimeMonthsOfStudy: 0,
  isReadOnly: false,
  isFulltimeAllowed: true,
  applicationOfferingIntensityValue: "Full Time",
};
