name: setup-env
description: setup environment

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: run dependencies
      shell: bash
      run: |
        pip install -r requirements.txt