apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-secrets
labels:
  project: ${PROJECT}
  service: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-creds
    stringData:
      ffa-api-database-name: ${FFA_API_DB_NAME}
      ffa-api-database-user: ${FFA_API_DB_USERNAME}
      ffa-api-database-password: ${FFA_API_DB_PASSWORD}
      ffa-bpm-database-name: ${FFA_BPM_DB_NAME}
      ffa-bpm-database-user: ${FFA_BPM_DB_USERNAME}
      ffa-bpm-database-password: ${FFA_BPM_DB_PASSWORD}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    value: ffa-patroni
  - name: PROJECT
    value: forms-flow-ai
  - name: FFA_API_DB_USERNAME
    generate: expression
    from: "[a-zA-Z0-9]{8}"
  - name: FFA_API_DB_NAME
    value: FFA_API_DB
  - name: FFA_API_DB_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: FFA_BPM_DB_USERNAME
    generate: expression
    from: "[a-zA-Z0-9]{8}"
  - name: FFA_BPM_DB_NAME
    value: FFA_BPM_DB
  - name: FFA_BPM_DB_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
