name: Build and Deploy to OpenShift/Camunda - DEV

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

jobs:
  # Print variables for logging and debugging purposes
  checkEnv:
    name: Check Env variables
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Build ID: ${{ github.event.number }}
          echo Git Pull Request Ref: ${{ github.event.pull_request.head.sha }}
          echo OC CLI Version: $(oc version)

  # Build Web, SIMS-Api and Workers
  build:
    name: Build Web, SIMS-Api and Workers
    environment: DEV
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true}}
    env:
      BUILD_ID: ${{ github.event.number }}
      BUILD_NAMESPACE: 0c27fb-tools
      BUILD_REF: ${{ github.base_ref }}
    steps:
      # Checkout the PR branch
      - name: Print env
        run: |
          echo BUILD ID: $BUILD_ID
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo BRANCH: $BUILD_REF
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      # Build the images
      - name: Build SIMS-API Image
        working-directory: "./devops"
        run: |
          make oc-build-api
      - name: Build Workers Image
        working-directory: "./devops"
        run: |
          make oc-build-workers
      - name: Build Web/Frontend Image
        working-directory: "./devops"
        run: |
          make oc-build-web

  # Deploy Web, SIMS-Api and Workers
  deployDev:
    name: Deploy Web, SIMS-Api and Workers to DEV environment
    runs-on: ubuntu-latest
    environment: DEV
    needs:
      - build
    env:
      BUILD_ID: ${{ github.event.number }}
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
      BUILD_REF: ${{ github.base_ref }}
      HOST_PREFIX: ${{ secrets.HOST_PREFIX }}
      BUILD_NAMESPACE: 0c27fb-tools
      KEYCLOAK_REALM: "jxoe2o46"
      KEYCLOAK_AUTH_URL: ${{ secrets.KEYCLOAK_AUTH_URL }}
      BCeID_WEB_SERVICE_WSDL: ${{ secrets.BCeID_WEB_SERVICE_WSDL }}
      FORMS_URL: ${{ secrets.FORMS_URL }}
      SITE_MINDER_LOGOUT_URL: ${{ secrets.SITE_MINDER_LOGOUT_URL }}
      RULE_ENGINE_URL: TO_BE_REMOVED
      FORMS_FLOW_API_URL: TO_BE_REMOVED
      ATBC_LOGIN_ENDPOINT: ${{ secrets.ATBC_LOGIN_ENDPOINT }}
      ATBC_ENDPOINT: ${{ secrets.ATBC_ENDPOINT }}
      SWAGGER_ENABLED: true
      APPLICATION_ARCHIVE_DAYS: 43
      BYPASS_APPLICATION_SUBMIT_VALIDATIONS: ${{ secrets.BYPASS_APPLICATION_SUBMIT_VALIDATIONS }}
      BYPASS_CRA_INCOME_VERIFICATION: ${{ secrets.BYPASS_CRA_INCOME_VERIFICATION }}
      API_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      WORKERS_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      API_PORT: ${{ secrets.API_PORT }}
      WEB_PORT: ${{ secrets.WEB_PORT }}
      API: ${{ format('{0}api-sims', secrets.HOST_PREFIX) }}
      WEB: ${{ format('{0}web-sims', secrets.HOST_PREFIX) }}
      WORKERS: ${{ format('{0}workers-sims', secrets.HOST_PREFIX) }}
      SWAGGER_NAME: ${{ format('{0}swagger', secrets.HOST_PREFIX) }}
      DATABASE_NAME_KEY: ${{ secrets.DATABASE_NAME_KEY }}
    steps:
      - name: Print env
        run: |
          echo BUILD ID: $BUILD_ID
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo NAMESPACE: $NAMESPACE
          echo BRANCH: $BUILD_REF
          echo HOST_PREFIX: $HOST_PREFIX
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v1
      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      # Deploy SIMS-Api
      - name: Deploy SIMS-API
        working-directory: "./devops/"
        run: |
          make oc-deploy-api
      # Deploy Workers
      - name: Deploy Workers
        working-directory: "./devops/"
        run: |
          make oc-deploy-workers
      # Deploy Deploy Web/Frontend
      - name: Deploy Web/Frontend
        working-directory: "./devops/"
        run: |
          make oc-deploy-web
