name: Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the PR branch.
      - name: Checkout Target Branch
        uses: actions/checkout@v3
        # Generate the coverage report
      - name: run API E2E tests on Docker
        working-directory: "./sources/"
        run: |
          make e2e-tests-api
      - name: SIMS API Code Coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "sources/packages/backend/coverage/api/clover.xml"
          threshold_alert: 1
          threshold_warning: 50
          threshold_metric: "lines"
