name: Crunchy DB - Install/Upgrade
run-name: Crunchy DB -  ${{ inputs.environment }} Crunchy DB in ${{ inputs.environment }} using ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment
      action:
        description: "Action"
        required: true
        type: choice
        options:
          - install
          - upgrade

jobs:
  manageCrunchyDB:
    name: ${{ inputs.environment }} Crunchy DB in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=${{ vars.OPENSHIFT_CLUSTER_URL }}
      - name: Manage Crunchy DB
        working-directory: "./devops/helm/crunchy-postgres/"
        run: |
          make ${{ inputs.action }} NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
