name: Create/update SIMS secrets to Openshift

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
      environmentNamespace:
        description: Openshift Environment Namespace
        required: true
        type: choice
        options:
          - 0c27fb-dev
          - 0c27fb-test
jobs:
  updateSecrets:
    name: Create or update secrets on Openshift
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      NAMESPACE: ${{ github.event.inputs.environmentNamespace }}
      API_INIT_BCeID_WEB_SERVICE_ONLINE_SERVICE_ID: ${{ secrets.BCeID_WEB_SERVICE_ONLINE_SERVICE_ID }}
      API_INIT_BCeID_WEB_SERVICE_REQUESTER_USER_GUID: ${{ secrets.BCeID_WEB_SERVICE_REQUESTER_USER_GUID }}
      API_INIT_BCeID_WEB_SERVICE_AUTH_USER_NAME: ${{ secrets.BCeID_WEB_SERVICE_AUTH_USER_NAME }}
      API_INIT_REQ_BCeID_WEB_SERVICE_AUTH_USER_PASSWORD: ${{ secrets.REQ_BCeID_WEB_SERVICE_AUTH_USER_PASSWORD }}
      API_INIT_WORKFLOW_SA_USER_NAME: ${{ secrets.WORKFLOW_SA_USER_NAME }}
      API_INIT_WORKFLOW_SA_PASSWORD: ${{ secrets.WORKFLOW_SA_PASSWORD }}
      API_INIT_FORMS_SA_USER_NAME: ${{ secrets.FORMS_SA_USER_NAME }}
      API_INIT_FORMS_SA_PASSWORD: ${{ secrets.FORMS_SA_PASSWORD }}
      API_INIT_SIMS_API_CLIENT_ID: ${{ secrets.SIMS_API_CLIENT_ID }}
      API_INIT_SIMS_API_CLIENT_SECRET: ${{ secrets.SIMS_API_CLIENT_SECRET }}
      API_INIT_CRA_REQUEST_FOLDER: ${{ secrets.CRA_REQUEST_FOLDER }}
      API_INIT_CRA_RESPONSE_FOLDER: ${{ secrets.CRA_RESPONSE_FOLDER }}
      API_INIT_CRA_PROGRAM_AREA_CODE: ${{ secrets.CRA_PROGRAM_AREA_CODE }}
      API_INIT_CRA_ENVIRONMENT_CODE: ${{ secrets.CRA_ENVIRONMENT_CODE }}
      API_INIT_ATBC_USERNAME: ${{ secrets.ATBC_USERNAME }}
      API_INIT_ATBC_PASSWORD: ${{ secrets.ATBC_PASSWORD }}
      API_INIT_ATBC_APP: ${{ secrets.ATBC_APP }}
      API_INIT_ESDC_REQUEST_FOLDER: ${{ secrets.ESDC_REQUEST_FOLDER }}
      API_INIT_ESDC_RESPONSE_FOLDER: ${{ secrets.ESDC_RESPONSE_FOLDER }}
      API_INIT_ESDC_ENVIRONMENT_CODE: ${{ secrets.ESDC_ENVIRONMENT_CODE }}
      API_INIT_SFAS_RECEIVE_FOLDER: ${{ secrets.SFAS_RECEIVE_FOLDER }}
      API_INIT_GC_NOTIFY_URL: ${{ secrets.GC_NOTIFY_URL }}
      API_INIT_GC_NOTIFY_API_KEY: ${{ secrets.GC_NOTIFY_API_KEY }}
      API_INIT_GC_NOTIFY_TO_ADDRESS: ${{ secrets.GC_NOTIFY_TO_ADDRESS }}
      API_INIT_ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
      API_INIT_ZEEBE_CLIENT_ID: ${{ secrets.ZEEBE_CLIENT_ID }}
      API_INIT_ZEEBE_CLIENT_SECRET: ${{ secrets.ZEEBE_CLIENT_SECRET }}
      API_INIT_ZEEBE_AUTHORIZATION_SERVER_URL: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
    steps:
      - name: Print env
        run: |
          echo NAMESPACE: $NAMESPACE
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      - name: Update secrets
        working-directory: "./devops/"
        run: |
          make init-api
