name: Deploy SIMS secrets to Openshift

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment

jobs:
  updateSecrets:
    name: Deploy secrets to Openshift
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
      SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      BCeID_WEB_SERVICE_ONLINE_SERVICE_ID: ${{ secrets.BCeID_WEB_SERVICE_ONLINE_SERVICE_ID }}
      BCeID_WEB_SERVICE_REQUESTER_USER_GUID: ${{ secrets.BCeID_WEB_SERVICE_REQUESTER_USER_GUID }}
      BCeID_WEB_SERVICE_AUTH_USER_NAME: ${{ secrets.BCeID_WEB_SERVICE_AUTH_USER_NAME }}
      BCeID_WEB_SERVICE_AUTH_USER_PASSWORD: ${{ secrets.BCeID_WEB_SERVICE_AUTH_USER_PASSWORD }}
      WORKFLOW_SA_USER_NAME: ${{ secrets.WORKFLOW_SA_USER_NAME }}
      WORKFLOW_SA_PASSWORD: ${{ secrets.WORKFLOW_SA_PASSWORD }}
      FORMS_SA_USER_NAME: ${{ secrets.FORMS_SA_USER_NAME }}
      FORMS_SA_PASSWORD: ${{ secrets.FORMS_SA_PASSWORD }}
      SIMS_API_CLIENT_ID: ${{ secrets.SIMS_API_CLIENT_ID }}
      SIMS_API_CLIENT_SECRET: ${{ secrets.SIMS_API_CLIENT_SECRET }}
      CRA_REQUEST_FOLDER: ${{ secrets.CRA_REQUEST_FOLDER }}
      CRA_RESPONSE_FOLDER: ${{ secrets.CRA_RESPONSE_FOLDER }}
      CRA_PROGRAM_AREA_CODE: ${{ secrets.CRA_PROGRAM_AREA_CODE }}
      CRA_ENVIRONMENT_CODE: ${{ secrets.CRA_ENVIRONMENT_CODE }}
      ATBC_USERNAME: ${{ secrets.ATBC_USERNAME }}
      ATBC_PASSWORD: ${{ secrets.ATBC_PASSWORD }}
      ATBC_APP: ${{ secrets.ATBC_APP }}
      ESDC_REQUEST_FOLDER: ${{ secrets.ESDC_REQUEST_FOLDER }}
      ESDC_RESPONSE_FOLDER: ${{ secrets.ESDC_RESPONSE_FOLDER }}
      ESDC_ENVIRONMENT_CODE: ${{ secrets.ESDC_ENVIRONMENT_CODE }}
      SFAS_RECEIVE_FOLDER: ${{ secrets.SFAS_RECEIVE_FOLDER }}
      GC_NOTIFY_URL: ${{ secrets.GC_NOTIFY_URL }}
      GC_NOTIFY_API_KEY: ${{ secrets.GC_NOTIFY_API_KEY }}
      GC_NOTIFY_TO_ADDRESS: ${{ secrets.GC_NOTIFY_TO_ADDRESS }}
      ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
      ZEEBE_CLIENT_ID: ${{ secrets.ZEEBE_CLIENT_ID }}
      ZEEBE_CLIENT_SECRET: ${{ secrets.ZEEBE_CLIENT_SECRET }}
      ZEEBE_AUTHORIZATION_SERVER_URL: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
    steps:
      - name: Print env
        run: |
          echo NAMESPACE: $NAMESPACE
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      - name: Update secrets
        working-directory: "./devops/"
        run: |
          make init-secrets
