name: Deploy to TEST in OpenShift

on:
  workflow_dispatch:
    inputs:
      buildRef:
        description: "Build Ref"
        required: true
        default: "main"
      buildId:
        description: "Build Id"
        required: true
        default: "NULL"
      resourcesFolder:
        description: "Folder with the resources to be deployed"
        required: true
        default: "BPMN/camunda-8"
      environment:
        required: true
        type: environment

env:
  APP_NAME: sims

jobs:
  deployTest:
    name: Deploy Web, SIMS-Api, Workers, and DB to TEST environment
    runs-on: ubuntu-latest
    env:
      BUILD_ID: ${{ github.event.inputs.buildId }}
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
      BUILD_NAMESPACE: 0c27fb-tools
      BUILD_REF: ${{ github.event.inputs.buildRef }}
      HOST_PREFIX: ${{ secrets.HOST_PREFIX }}
      KEYCLOAK_REALM: "jxoe2o46"
      KEYCLOAK_AUTH_URL: "https://test.oidc.gov.bc.ca/auth/"
      BCeID_WEB_SERVICE_WSDL: "https://gws1.test.bceid.ca/webservices/Client/V10/BCeIDService.asmx?wsdl"
      RULE_ENGINE_URL: "https://test-aest-ffa-bpm.apps.silver.devops.gov.bc.ca/camunda/engine-rest"
      FORMS_URL: "https://test-aest-ffa-forms.apps.silver.devops.gov.bc.ca"
      SITE_MINDER_LOGOUT_URL: "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi"
      FORMS_FLOW_API_URL: "https://test-aest-ffa-api.apps.silver.devops.gov.bc.ca"
      ATBC_LOGIN_ENDPOINT: "https://auth.at-bc.ca/api/login"
      ATBC_ENDPOINT: "https://sabc.at-bc.ca/api"
      SWAGGER_ENABLED: true
      APPLICATION_ARCHIVE_DAYS: 43
      BYPASS_APPLICATION_SUBMIT_VALIDATIONS: true
      API_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      WORKERS_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      API_PORT: ${{ secrets.API_PORT }}
      WEB_PORT: ${{ secrets.WEB_PORT }}
      API: ${{ format('{0}api-{1}', secrets.HOST_PREFIX, $APP_NAME) }}
      WEB: ${{ format('{0}web-{1}', secrets.HOST_PREFIX, $APP_NAME) }}
      WORKERS: ${{ format('{0}workers-{1}', secrets.HOST_PREFIX, $APP_NAME) }}
      SWAGGER_NAME: ${{ format('{0}swagger', secrets.HOST_PREFIX) }}
      DATABASE_NAME_KEY: ${{ secrets.DATABASE_NAME_KEY }}
    steps:
      - name: Print env
        run: |
          echo BUILD ID: $BUILD_ID
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo NAMESPACE: $NAMESPACE
          echo BRANCH: $BUILD_REF
          echo HOST_PREFIX: $HOST_PREFIX
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v1
      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      # Deploy SIMS-Api
      - name: Deploy SIMS-API
        working-directory: "./devops/"
        run: |
          make oc-deploy-api
      # Deploy Workers
      - name: Deploy Workers
        working-directory: "./devops/"
        run: |
          make oc-deploy-workers
      # Deploy Deploy Web/Frontend
      - name: Deploy Web/Frontend
        working-directory: "./devops/"
        run: |
          make oc-deploy-web
  deployCamundaDefinitions:
    name: Deploy BPMNs and DMNs to Camunda
    needs:
      - deployTest
    uses: ./.github/workflows/camunda-definitions-deploy.yml
    secrets: inherit
    with:
      resourcesFolder: ${{ github.event.inputs.resourcesFolder }}
      environment: ${{ github.event.inputs.environment }}
  deployFormioDefinitions:
    name: Deploy Form.io definitions
    needs:
      - deployTest
    uses: ./.github/workflows/formio-definitions-deploy.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
