name: Deploy Camunda Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Openshift Environment'
        required: true
        type: environment
      gitRef:
        description: 'Github reference'
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      gitRef:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Camunda resources
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
      ZEEBE_AUTHORIZATION_SERVER_URL: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
      ZEEBE_CLIENT_ID: ${{ secrets.ZEEBE_CLIENT_ID }}
      ZEEBE_CLIENT_SECRET: ${{ secrets.ZEEBE_CLIENT_SECRET }}
    steps:
      - name: Print env variables
        run: |
          echo ZEEBE_ADDRESS: $ZEEBE_ADDRESS
          echo RESOURCES_FOLDER: $RESOURCES_FOLDER
      - name: Checkout Target Branch
        uses: actions/checkout@v3
        with:
          ref:  ${{ github.event.inputs.gitRef }}
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Downloading packages
        working-directory: "./sources/packages/backend"
        run: npm ci
      - name: Executing deployment
        working-directory: "./sources/packages/backend"
        run: npm run deploy:camunda:definitions
