name: Load Test - Deploy Gateway
run-name: Deploy Load Test Gateway from ${{ github.ref_name }} to ${{ inputs.environment }}
permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment

env:
  NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
  BUILD_REF: ${{ github.ref_name }}
  BUILD_NAMESPACE: ${{ vars.BUILD_NAMESPACE }}
  HOST_PREFIX: ${{ secrets.HOST_PREFIX }}
  KEYCLOAK_REALM: ${{ vars.KEYCLOAK_REALM }}
  KEYCLOAK_AUTH_URL: ${{ secrets.KEYCLOAK_AUTH_URL }}
  LOAD_TEST_GATEWAY_SECRET_NAME: ${{ secrets.LOAD_TEST_GATEWAY_SECRET_NAME }}
  TLS_CERTIFICATE: ${{ secrets.TLS_CERTIFICATE }}
  TLS_KEY: ${{ secrets.TLS_KEY }}
  TLS_CA_CERTIFICATE: ${{ secrets.TLS_CA_CERTIFICATE }}

jobs:
  deploy-load-test-gateway:
    name: Deploy Load Test Gateway
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"
      - name: Print env
        run: |
          echo Deploy Environment: ${{ inputs.environment }}
          echo GIT REF: ${{ env.BUILD_REF }}
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo OC CLI Version: $(oc version)
      - name: Checkout Target Branch
        uses: actions/checkout@v7
        with:
          ref: ${{ env.BUILD_REF }}
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=${{ vars.OPENSHIFT_CLUSTER_URL }}
      - name: Deploy Load Test Gateway
        working-directory: "./devops/"
        run: |
          make oc-deploy-load-test-gateway
