name: Prune Images
run-name: Pruning stale image tags
permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *" # Runs at 6 AM Pacific every day

jobs:
  prune-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: devops/image-pruner

      - name: Prune ImageStream Tags
        run: npm run prune
        working-directory: devops/image-pruner
        env:
          SA_TOKEN: ${{ secrets.SA_TOKEN }}
          OPENSHIFT_URL: ${{ vars.OPENSHIFT_CLUSTER_URL }}
          LICENSE_PLATE: ${{ vars.OPENSHIFT_LICENSE_PLATE }}
