name: Prune Images
run-name: Pruning all but the most recent ${{ inputs.minTags }} tags prior to what is deployed in ${{ inputs.environment }}
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment"
        required: true
        options:
          - dev
          - test
          - prod
        default: "dev"
      applications:
        description: "Comma separated list of application Image Streams to prune"
        required: true
        default: "web-sims, api-sims, queue-consumers-sims, workers-sims"
      ocjobs:
        description: "Comma separated list of job Image Streams to prune"
        required: true
        default: "migrations-job"
      prefix:
        description: "Branch prefix to restrict pruning to"
        required: false
        default: "main"
      minTags:
        description: "Minimum number of prefix (main) tags to keep per Image Stream"
        required: false
        default: "2"
  schedule:
    - cron: "0 14 * * *" # Runs at 6 AM Pacific every day

jobs:
  prune-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "26.x"

      - name: Install dependencies
        run: npm ci
        working-directory: devops/image-pruner

      - name: Prune ImageStream Tags
        run: npm run prune
        working-directory: devops/image-pruner
        env:
          SA_TOKEN: ${{ secrets.SA_TOKEN }}
          OPENSHIFT_URL: ${{ vars.OPENSHIFT_CLUSTER_URL }}
          LICENSE_PLATE: ${{ vars.OPENSHIFT_LICENSE_PLATE }}
          ENVIRONMENT: ${{ inputs.environment || 'dev' }}
          APPLICATIONS: ${{ inputs.applications || 'web-sims, api-sims, queue-consumers-sims, workers-sims' }}
          OCJOBS: ${{ inputs.ocjobs || 'migrations-job' }}
          PREFIX: ${{ inputs.prefix || 'main' }}
          MIN_TAGS: ${{ inputs.minTags || '2' }}
