name: Redis Cluster - Install/Upgrade
run-name: Redis Cluster - ${{ inputs.environment }} Redis Cluster in ${{ inputs.environment }} using ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment
      action:
        description: "Action"
        required: true
        type: choice
        options:
          - install
          - upgrade

jobs:
  manageRedisCluster:
    name: ${{ inputs.environment }} Redis Cluster in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=${{ vars.OPENSHIFT_CLUSTER_URL }}
      - name: Manage Redis Cluster
        working-directory: "./devops/helm/redis-cluster/"
        run: |
          if [ "${{ inputs.action }}" == "install" ]; then
            make install NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
          elif [ "${{ inputs.action }}" == "upgrade" ]; then
            PASSWORD=$(oc get secret redis-cluster -n ${{ secrets.OPENSHIFT_ENV_NAMESPACE }} -o jsonpath="{.data.redis-password}" | base64 --decode)
            make upgrade NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }} PASSWORD=$PASSWORD
          fi
