name: Release - Deploy Form.io resources
run-name: Release - Deploy Form.io resources from ${{ inputs.gitRef }} to ${{ inputs.environment }}
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment
      gitRef:
        description: "Github reference"
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      gitRef:
        required: true
        type: string
    secrets:
      FORMS_SECRET_NAME:
        required: true
      OPENSHIFT_SIMS_CREDS_NAME:
        required: true
      HOST_PREFIX:
        required: true
      OPENSHIFT_ENV_NAMESPACE:
        required: true

jobs:
  deploy:
    name: Deploy Form.io definitions
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
      BUILD_NAMESPACE: ${{ vars.BUILD_NAMESPACE }}
      BUILD_REF: ${{ inputs.gitRef }}
      MIGRATIONS_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      HOST_PREFIX: ${{ secrets.HOST_PREFIX }}
      FORMS_SECRET_NAME: ${{ secrets.FORMS_SECRET_NAME }}
    steps:
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"
      - name: Print env
        run: |
          echo BUILD NAMESPACE: "$BUILD_NAMESPACE"
          echo OC CLI Version: $(oc version)
      - name: Checkout Target Branch
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.gitRef }}
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=${{ vars.OPENSHIFT_CLUSTER_URL }}
      - name: Run deploy form definitions
        working-directory: "./devops/"
        run: |
          make oc-run-migrations MIGRATION_COMMAND="cd forms && npm run deploy"
