name: Release - Deploy all

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Git Ref (e.g. v1.0.0 or v1.0.0-prerelease.1)"
        required: true
        default: ""
      environment:
        description: "Environment"
        required: true
        type: environment
      deployCamundaDefinitions:
        description: "Deploy Camunda BPMN/DMN from main"
        type: boolean
        default: true
      deployFormioDefinitions:
        description: "Deploy Form.io forms from main"
        type: boolean
        default: true
  workflow_call:
    inputs:
      gitRef:
        required: true
        type: string
      environment:
        required: true
        type: string
      deployCamundaDefinitions:
        required: true
        type: string
      deployFormioDefinitions:
        required: true
        type: string
    secrets:
      SA_TOKEN:
        required: true
      OPENSHIFT_ENV_NAMESPACE:
        required: true
      HOST_PREFIX:
        required: true
      KEYCLOAK_AUTH_URL:
        required: true
      BCeID_WEB_SERVICE_WSDL:
        required: true
      SITE_MINDER_LOGOUT_URL:
        required: true
      ATBC_LOGIN_ENDPOINT:
        required: true
      ATBC_ENDPOINT:
        required: true
      BYPASS_APPLICATION_SUBMIT_VALIDATIONS:
        required: true
      BYPASS_CRA_INCOME_VERIFICATION:
        required: true
      OPENSHIFT_SIMS_CREDS_NAME:
        required: true
      FORMS_SECRET_NAME:
        required: true
      QUEUE_PREFIX:
        required: true
      API_PORT:
        required: true
      WEB_PORT:
        required: true

jobs:
  # Run DB migrations.
  run-db-migrations:
    name: Run db-migrations
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
      BUILD_REF: ${{ github.event.inputs.gitRef }}
      HOST_PREFIX: ${{ secrets.HOST_PREFIX }}
      BUILD_NAMESPACE: 0c27fb-tools
      KEYCLOAK_REALM: "aestsims"
      KEYCLOAK_AUTH_URL: ${{ secrets.KEYCLOAK_AUTH_URL }}
      BCeID_WEB_SERVICE_WSDL: ${{ secrets.BCeID_WEB_SERVICE_WSDL }}
      SITE_MINDER_LOGOUT_URL: ${{ secrets.SITE_MINDER_LOGOUT_URL }}
      ATBC_LOGIN_ENDPOINT: ${{ secrets.ATBC_LOGIN_ENDPOINT }}
      ATBC_ENDPOINT: ${{ secrets.ATBC_ENDPOINT }}
      SWAGGER_ENABLED: true
      APPLICATION_ARCHIVE_DAYS: 43
      BYPASS_APPLICATION_SUBMIT_VALIDATIONS: ${{ secrets.BYPASS_APPLICATION_SUBMIT_VALIDATIONS }}
      BYPASS_CRA_INCOME_VERIFICATION: ${{ secrets.BYPASS_CRA_INCOME_VERIFICATION }}
      API_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      WORKERS_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      QUEUE_CONSUMERS_SECRET_NAME: ${{ secrets.OPENSHIFT_SIMS_CREDS_NAME }}
      FORMS_SECRET_NAME: ${{ secrets.FORMS_SECRET_NAME }}
      QUEUE_PREFIX: ${{ secrets.QUEUE_PREFIX }}
      API_PORT: ${{ secrets.API_PORT }}
      WEB_PORT: ${{ secrets.WEB_PORT }}
      DATABASE_NAME_KEY: ${{ secrets.DATABASE_NAME_KEY }}
    steps:
      - name: Print env
        run: |
          echo BUILD NAMESPACE: $BUILD_NAMESPACE
          echo BRANCH: ${{ github.event.inputs.gitRef }}
          echo HOST_PREFIX: $HOST_PREFIX
      - name: Checkout Target Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.gitRef }}
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443
      - name: Run db-migrations
        working-directory: "./devops/"
        run: |
          make oc-run-db-migrations
