name: Tests

on: [pull_request]

jobs:
  api-e2e-tests:
    name: SIMS API E2E Tests
    environment: DEV
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: aest-sims
      BUILD_ID: ${{ github.event.number }}
      POSTGRES_PASSWORD: bcgov!
      BUILD_REF: ${{ github.base_ref }}
      POSTGRES_DB: sims
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      REDIS_STANDALONE_MODE: "true"
      QUEUE_PREFIX: "{sims-local}"
      API_PORT: 3000
      APP_PORT: 8080
      QUEUE_CONSUMERS_PORT: 3001
      DB_SCHEMA: sims
      KEYCLOAK_REALM: "aestsims"
      KEYCLOAK_AUTH_URL: "https://dev.loginproxy.gov.bc.ca/auth/"
      BCeID_WEB_SERVICE_WSDL: "https://gws1.test.bceid.ca/webservices/Client/V10/BCeIDService.asmx?wsdl"
      E2E_TEST_STUDENT_USERNAME: student_e2e_test
      E2E_TEST_STUDENT_PASSWORD: ${{ secrets.TEST_STUDENT_PASSWORD }}
      E2E_TEST_AEST_BUSINESS_ADMINISTRATORS_USER: ministry-user-aest-business-administrators@e2e-tests
      E2E_TEST_AEST_BUSINESS_ADMINISTRATORS_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
      E2E_TEST_AEST_OPERATIONS_USER: ministry-user-aest-operations@e2e-tests
      E2E_TEST_AEST_OPERATIONS_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
      E2E_TEST_AEST_OPERATIONS_ADMINISTRATORS_USER: ministry-user-aest-operations-administrators@e2e-tests
      E2E_TEST_AEST_OPERATIONS_ADMINISTRATORS_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
      E2E_TEST_AEST_MOF_OPERATIONS_USER: ministry-user-mof-operations@e2e-tests
      E2E_TEST_AEST_MOF_OPERATIONS_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
    steps:
      # Checkout the PR branch.
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      # Generate the coverage report for API
      - name: Run Tests
        working-directory: "./sources/"
        run: |
          make e2e-tests-api
      - name: Tests Coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status_context: "E2E SIMS API Coverage Report"
          comment_context: "E2E SIMS API Coverage Report"
          coverage_path: "sources/packages/backend/coverage/api/clover.xml"
          threshold_alert: 1
          threshold_warning: 50
          threshold_metric: "lines"
          comment_footer: false
  workers-e2e-tests:
    name: Workflow Workers E2E Tests
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: aest-sims
      BUILD_ID: ${{ github.event.number }}
      POSTGRES_PASSWORD: bcgov!
      BUILD_REF: ${{ github.base_ref }}
      POSTGRES_DB: sims
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      REDIS_STANDALONE_MODE: "true"
      QUEUE_PREFIX: "{sims-local}"
      API_PORT: 3000
      APP_PORT: 8080
      QUEUE_CONSUMERS_PORT: 3001
      DB_SCHEMA: sims
    steps:
      # Checkout the PR branch.
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      # Generate the coverage report for Workflow Workers
      - name: Run Tests
        working-directory: "./sources/"
        run: |
          make e2e-tests-workers
      - name: Tests Coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status_context: "E2E Workflow Workers Coverage Report"
          comment_context: "E2E Workflow Workers Coverage Report"
          coverage_path: "sources/packages/backend/coverage/workers/clover.xml"
          threshold_alert: 1
          threshold_warning: 50
          threshold_metric: "lines"
          comment_footer: false
  queue-consumers-e2e-tests:
    name: Queue Consumers E2E Tests
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: aest-sims
      BUILD_ID: ${{ github.event.number }}
      POSTGRES_PASSWORD: bcgov!
      BUILD_REF: ${{ github.base_ref }}
      POSTGRES_DB: sims
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      REDIS_STANDALONE_MODE: "true"
      QUEUE_PREFIX: "{sims-local}"
      API_PORT: 3000
      APP_PORT: 8080
      QUEUE_CONSUMERS_PORT: 3001
      DB_SCHEMA: sims
    steps:
      # Checkout the PR branch.
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      # Generate the coverage report for Queue Consumers
      - name: Run Tests
        working-directory: "./sources/"
        run: |
          make e2e-tests-queue-consumers
      - name: Tests Coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status_context: "E2E Queue Consumers Coverage Report"
          comment_context: "E2E Queue Consumers Coverage Report"
          coverage_path: "sources/packages/backend/coverage/queue-consumers/clover.xml"
          threshold_alert: 1
          threshold_warning: 50
          threshold_metric: "lines"
          comment_footer: false
  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the PR branch.
      - name: Checkout Target Branch
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      # Run units tests and generate the coverage report.
      - name: Run Tests
        working-directory: "./sources/"
        run: |
          make backend-unit-tests
      - name: Tests Coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status_context: "Backend Unit Tests Coverage Report"
          comment_context: "Backend Unit Tests Coverage Report"
          coverage_path: "sources/packages/backend/coverage/unit-tests/clover.xml"
          threshold_alert: 1
          threshold_warning: 50
          threshold_metric: "lines"
          comment_footer: false
